### ISSUE TITLE
[BUG] Unable to create a folder containing "#" in the name using Add-PnPFolder

### ISSUE THREAD

**Issue by ShawnPOWER** [pnp/powershell#1024]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting

- Issue

### Expected behavior #
Please describe what output you expect to see from the PnP PowerShell Cmdlets

- When creating a new folder with `Add-PnPFolder`, I would expect a folder be created with the specified name. As long as it doesn't violate the character restrictions.

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.

- When creating a new folder with `Add-PnPFolder`, if I include a "#" in the `-Name` parameter an error is returned and the folder is not made. The error is: "Add-PnPFolder: The argument must be a single folder name and cannot contain path characters. (Parameter 'folderName')"

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)

- `Connect-PnPOnline`
- `Add-PnPFolder -Name "Test #1" -Folder "Test Library"`

> "Add-PnPFolder: The argument must be a single folder name and cannot contain path characters. (Parameter 'folderName')"

- `Add-PnPFolder -Name "Test 1" -Folder "Test Library"`
-- The file is created due to the "#" missing from the `-Name` paremeter.
- `Get-PnPException`
```
Message          : The argument must be a single folder name and cannot contain path characters. (Parameter 'folderName')     
Stacktrace       :    at Microsoft.SharePoint.Client.FileFolderExtensions.CreateFolder(Folder parentFolder, String folderName)
                      at PnP.PowerShell.Commands.Files.AddFolder.ExecuteCmdlet() in D:\a\powershell\powershell\src\Commands\Files\AddFolder.cs:line 25
                      at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord() in D:\a\powershell\powershell\src\Commands\Base\PnPSharePointCmdlet.cs:line 91
ScriptLineNumber : 1
```

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

- 1.7.22 (nightly)

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by YuriySamorodov** [comment]
Same for me. However I am able to create a folder with a hashtag in its name from the web UI:
![image](https://user-images.githubusercontent.com/5260172/130376879-f17d53b3-98c6-406c-9bfb-5a3ad4b0652e.png)

**Comment by ShawnPOWER** [comment]
Thank you @YuriySamorodov, I didn't attempt `Rename-PnPFolder`, good to know.

**Comment by gautamdsheth** [comment]
Issue has been fixed in the latest nightly builds.
Please reopen it if it still exists !

**Comment by ShawnPOWER** [comment]
Thank you @gautamdsheth. However, it is still not working for me in version 1.7.62. Same results as above.

**Comment by KoenZomers** [comment]
PR submitted for fixing this: https://github.com/pnp/pnpframework/pull/476

Please wait for this PR to be merged, wait for the next day and try again using the by then latest prerelease.
