### ISSUE TITLE
Set-PnPPageWebPart - CSOM service exception [BUG]

### ISSUE THREAD

**Issue by jmunozcastro** [pnp/powershell#1039]
### Reporting an Issue or Missing Feature
Set-PnPPageWebPart command is throwing error when I try to set client side webpart through PowerShell.

### Expected behavior 
A property inside in the properties JSON of the web part should be set

### Actual behavior 
Getting following error:

      HttpResponseCode: 200
      Message: Column 'HPR Departments' does not exist. It may have been deleted by another user.
      ClientRequestId: 4158e99f-40a1-1000-2128-5f9f6e2d73b4
      ErrorTypeName: "System.ArgumentException"
      
      PnP.Core.CsomServiceException: CSOM service exception
         at PnP.Core.Services.BatchClient.ProcessCsomBatchResponse(CsomBatch csomBatch, String batchResponse, HttpStatusCode statusCode)
         at PnP.Core.Services.BatchClient.<ExecuteCsomBatchAsync>d__53.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at PnP.Core.Services.BatchClient.<ExecuteBatch>d__36.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at PnP.Core.Model.BaseDataModel`1.<RequestAsync>d__99.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at PnP.Core.Model.BaseDataModel`1.<RawRequestAsync>d__102.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at PnP.Core.Model.SharePoint.ListItem.<SystemUpdateAsync>d__83.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at PnP.Core.Model.SharePoint.Page.<SaveAsync>d__131.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at PnP.Core.Model.SharePoint.Page.Save(String pageName)
         at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord()

### Steps to reproduce behavior

`Set-PnPPageWebPart -Page Home -Identity 250d6a30-3909-441c-b74c-9b7bf6e1767a -PropertiesJson { ""content":  "<a href='./' target='_blank'>Test</a>"" } -ErrorAction Stop`

***Note:*** Actually, the error occurs regardless of the content of the PropertiesJson variable, as it is always presented if the library where the page is located has columns whose internal name is different from the display name.
In my case into SitePages library exists a column called 'HPRDepartments' as display name and 'HPR_x0020_Departments' as internal name. But when the space is added to Display name like 'HPR Departments' the error disappear.

The bug is similar to [issue 631](https://githubmemory.com/repo/pnp/powershell/issues/631)

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)
Manifest   1.7.0      PnP.PowerShell

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
@jmunozcastro - can you try with the latest PnP PowerShell, preferably a nightly build of 1.8.0 and let us know ?

**Comment by veronicageek** [comment]
Closing as no response.
