### ISSUE TITLE
[BUG]Unable to perform actions against sharepoint site using AZURE App - ClientId and ClientSecret

### ISSUE THREAD

**Issue by ash3434** [pnp/powershell#1450]
### Reporting an Issue or Missing Feature
When connecting to any site (root site collection or web) using Connect-PnPOnline with ClientId and ClientSecret, subsequent requests give a 401 response - "The remote server returned an error: (401) Unauthorized".

### Expected behavior 
Should be able to function  
Connect-PnPOnline -Url $Uri -ClientID $clientId -ClientSecret $clientSecret -WarningAction Ignore

### Actual behavior 
Seen through - Get-PnPException ( used after the Connect-PnPOnline command)
Message          : The remote server returned an error: (401) Unauthorized.
Stacktrace       :    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
                      at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 
                   promise, Boolean requiresSynchronization)
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.SharePoint.Client.SPWebRequestExecutor.<ExecuteAsync>d__20.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.SharePoint.Client.ClientContext.<GetFormDigestInfoPrivateAsync>d__37.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.SharePoint.Client.ClientContext.<EnsureFormDigestAsync>d__36.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__28.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__6.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__6.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.SharePoint.Client.ClientObjectExtensions.<EnsurePropertiesImplementation>d__8`1.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.SharePoint.Client.ClientObjectExtensions.EnsureProperties[T](T clientObject, Expression`1[] propertySelector)
                      at PnP.PowerShell.Commands.GetWeb.ExecuteCmdlet()
                      at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord()
ScriptLineNumber : 95

### Steps to reproduce behavior
1. Register an Azure App and generate ClientSecret instead of using certificate option
2. Assign Application Permission for SharePoint - "Sites.ReadWrite.All"
3. Grant admin consent

### What is the version of the Cmdlet module you are running?
1.8.0

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows

Please provide guidance how to authenticate via PnP fw

**Comment by gautamdsheth** [comment]
This is not a supported scenario by Microsoft.
To perform actions against SharePoint , you will require Client Id and Certificate.

https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azuread

![image](https://user-images.githubusercontent.com/8832018/146316062-d0cab2dc-7920-4233-adec-cfe7f5eb983b.png)
