### ISSUE TITLE
Add-PnPNavigationNode Navigation Node Collection is null

### ISSUE THREAD

**Issue by MedinaFab** [pnp/powershell#175]
I have installed new PowerShell version (after a painful experience since older version didn't want to uninstall), as per advised pnp/pnpframework#129. I tried this command but still failed. Copying @jansenbe. Thanks in advance for your help. Really thankful for PNP! 😃

`Add-PnPNavigationNode -Title "Privacy Policy" -Url "http://www.company.com/privacy/" -Location "Footer"`

Error obtained:
`Add-PnPNavigationNode: Navigation Node Collection is null`

Get-PnPException
`
Message          : Navigation Node Collection is null
Stacktrace       :    at PnP.PowerShell.Commands.Branding.AddNavigationNode.ExecuteCmdlet()
                      at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord()
ScriptLineNumber : 1`

**Comment by erwinvanhunen** [comment]
What type of site do you try to set the footer on? You can only set the footer on a Modern Communications Site and a Modern Team Site, whereas the latter will not actually show it though (confusingly enough). 

You can retrieve the underlying sitedefinition of a site like this:

```powershell
$web = Get-PnPWeb -Includes Configuration,WebTemplate
"$($web.WebTemplate)#$($web.Configuration)"
```

The result on your site should either be `SITEPAGEPUBLISHING#0`. While you should be able to set the footer value for modern team sites, the site itself will actually not render it. A check you can do is if you in the site click the cog at the top right, select 'change the look'. If in the resulting list a 'Footer' entry is present you should be able to add a footer link.

Having said that, we'll have a look if we can make the error message a bit more descriptive.

**Comment by MedinaFab** [comment]
> ```powershell
> $web = Get-PnPWeb -Includes Configuration,WebTemplate
> "$($web.WebTemplate)#$($web.Configuration)"
> ```

It is SITEPAGEPUBLISHING#0
It is a modern communication site. Thanks @erwinvanhunen! Honor to receive a reply from you. 😃 Just saw this morning the PnP weekly podcast to try to understand this new PowerShell a bit more.

I have been using PnP for quite a while now and one of the main things I used to do when we transitioned to modern is to run jobs to update the hub menu for all hub sites and was able to make the footer work with XML. However that stopped working months ago and this is the script I need to complete my tasks. The only workaround is to manually add dummy link, delete it and then the script works as it was logged here pnp/pnp-sites-core#2740. Looking forward to a resolution on this. Thanks.

**Comment by erwinvanhunen** [comment]
Okay. That explains a bit. The footer structure implementation in a site is a bit 'convoluted' to say the least.  The actual footer links are stored in the site navigation object, at a non-documented location. We found out where it is located (which id) but we might have missed a change in the way they store it. As said: it's not documented, so we're doing a bit of reverse engineering here. I will have a look.

**Comment by erwinvanhunen** [comment]
I just checked with a freshly created communication site,  one created through the UI, and one created with New-PnPSite, and immediately added a navigation node to the footer, but I have no issues...

Given that we use REST API calls behind the scenes: how exactly do you connect with PnP PowerShell? And which version are you running of PnP PS?

**Comment by MedinaFab** [comment]
`Connect-PnPOnline -Url "https://XXXXX.sharepoint.com/sites/XXXXX" -UseWebLogin`

 ```
Get-Module *PnP* -ListAvailable | Select-Object Name,Version | Sort-Object Version -Descending

Name           Version
----           -------
PnP.PowerShell 1.2.0
```

I used this script to add a node. 
`Add-PnPNavigationNode -Title "Privacy Policy" -Url "http://www.XX.com/privacy/" -Location "Footer"`

Full script and error here (some things are masked):
```
PS C:\Users\0_XX.XX> Connect-PnPOnline -Url "https://xxxx.sharepoint.com/sites/marketingphotos" -UseWebLogin
PS C:\Users\0_XX.XX> Add-PnPNavigationNode -Title "Privacy Policy" -Url "http://www.msn.com/privacy/" -Location "Footer"
Add-PnPNavigationNode: Navigation Node Collection is null
```

**Comment by erwinvanhunen** [comment]
Straight after you receive the exception, can you enter `Get-PnPException` and post the results here? It helps us a bit better to figure out where the error occurs as it could be related to the authentication (-UseWebLogin).

**Comment by MedinaFab** [comment]
```
PS C:\Users\X.X> Get-PnPException

Message          : Navigation Node Collection is null
Stacktrace       :    at PnP.PowerShell.Commands.Branding.AddNavigationNode.ExecuteCmdlet()
                      at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord()
ScriptLineNumber : 1
```

**Comment by erwinvanhunen** [comment]
Thank you. Unfortunately this didn't help much. I was hoping to see a bit bigger stacktrace. But there is nothing we can do about that right now. Okay. 

Did you try it on an existing site, or have you also tried on a freshly created communication site? I'm wondering if something in that specific site collection navigation structure if 'off'. Also, can you modify the footer from the UI in that site? I mean, does that still work?

**Comment by MedinaFab** [comment]
I see the problem after troubleshooting more! 
I created a new site manually, then applied script to add the Navigation Node and it works. But typically, I run it as below.
(1) Connect (2) Add logo (3) add nav nodes. Adding the logo first causes the issue and prevents me from adding the nodes.

```
PS C:\Users\X.X> Connect-PnPOnline -Url "https://X.sharepoint.com/sites/FooterTest3" -UseWebLogin
PS C:\Users\X.X> Set-PnPFooter -Title "" -LogoUrl "https://www.companyX.com/wp-content/uploads/2019/08/XXWhite_382x75px.png"
PS C:\Users\X.X> Add-PnPNavigationNode -Title "Privacy Policy" -Url "http://www.msn.com/privacy/" -Location "Footer"
Add-PnPNavigationNode: Navigation Node Collection is null
```

**Comment by MedinaFab** [comment]
For now, my workaround is to (1) apply nodes (2) set image. This seems to work for me and you can feel free to close this issue if need to but there may be underlying issue when you first apply logo unless I am setting up the command incorrectly. Up to you @erwinvanhunen. Happy with the help you provided!

**Comment by erwinvanhunen** [comment]
It seems that settings the logo first will not produce the required navigation node structure. This is handled in the PnP Framework so I will move this issue to the PnP Framework repository for further investigation.
