### ISSUE TITLE
[BUG] Get-PnPFile cannot retrieve urls with parens

### ISSUE THREAD

**Issue by xaviv** [pnp/powershell#1751]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
When the url used at Get-PnPFile cmdlet contains parens, it returns a sharepoint exception

### Expected behavior 
Accept parens and any special char on url, or accept http entities instead

### Actual behavior 
PS P:\GPM\101-Grid Integration\R&D Projects> $fitxer="/teams/GPM-shared-storage/Shared Documents/100_Operations/101_Grid Compliance/R&D Projects/GR0-042/Desenvolupament/DOCUMENTACIÓ/NORMATIVES-ESPECIFICACIONS/Puerto Rico/Especificaciones Ilumina/PSSE PUERTO RICO/Arxius simulació Ilumina/GPTech Voltage Regulation System%28VRS%29 for Ilumina Jan19 2012/VRS Version A1 - Ilumina/GPTVRS_A1_V312_ILUMINA.obj"
PS P:\GPM\101-Grid Integration\R&D Projects> get-pnpfile -url $fitxer -filename  "gptvrs_a1_v312_ilumina.obj" -path . -asfile -force
Get-PnPFile: One or more errors occurred. (SharePoint Rest service exception)
PS P:\GPM\101-Grid Integration\R&D Projects> get-pnpexception

Message          : One or more errors occurred. (SharePoint Rest service exception)
Stacktrace       :    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
                      at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
                      at PnP.PowerShell.Commands.Files.GetFile.ExecuteCmdlet() in c:\build\src\Commands\Files\GetFile.cs:line 150
                      at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord() in c:\build\src\Commands\Base\PnPSharePointCmdlet.cs:line 89
ScriptLineNumber : 1

### What is the version of the Cmdlet module you are running?
Manifest   1.10.0                PnP.PowerShellManifest   1.10.0                PnP.PowerShell
Powershell 7.2

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by bfloog** [comment]
Same here all of a sudden.

```powershell
PS C:\Users\ajleer> Get-PnPFile -Url "/sites/PointofSale/Shared Documents/General/Forms `(Food`)/Menu Items + Online.xlsm" -AsFile -Path "C:\Users\ajleer\OneDrive - SomeCompany\Projects\Simph-Menu-Item-Find-York\src\xlsx" -Filename "Grantville Menu Item Request x.xlsm" -Force
Get-PnPFile : One or more errors occurred.
At line:1 char:1
+ Get-PnPFile -Url "/sites/PointofSale/Shared Documents/General/For ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPFile], AggregateException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Files.GetFile
```

**Comment by bfloog** [comment]
If this helps:

```powershell
PS C:\Users\ajleer> Get-Module -ListAvailable | ? { $_.Name -like "*Pn*" }


    Directory: C:\Users\ajleer\Documents\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
PSImplicitRemotingMessage, Modify-PSImplicitRemotingParameters, Get-PSImplicitRemotingSessionOption...}
Manifest   1.10.0     PnP.PowerShell                      {Add-PnPAdaptiveScopeProperty, Add-PnPPropertyBagValue, Copy-PnPFolder, Export-PnPClientSidePage...}
Manifest   1.9.0      PnP.PowerShell                      {Add-PnPClientSidePageSection, Add-PnPClientSideText, Add-PnPClientSideWebPart, Copy-PnPFolder...}
Manifest   1.8.0      PnP.PowerShell                      {Add-PnPClientSidePage, Add-PnPClientSidePageSection, Add-PnPClientSideText, Add-PnPClientSideWebPart...}
Manifest   1.7.0      PnP.PowerShell                      {Add-PnPClientSidePage, Add-PnPClientSidePageSection, Add-PnPClientSideText, Add-PnPClientSideWebPart...}
Manifest   1.6.0      PnP.PowerShell                      {Add-PnPClientSidePage, Add-PnPClientSidePageSection, Add-PnPClientSideText, Add-PnPClientSideWebPart...}
Manifest   1.5.0      PnP.PowerShell                      {Add-PnPClientSidePage, Add-PnPClientSidePageSection, Add-PnPClientSideText, Add-PnPClientSideWebPart...}


    Directory: C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   1.0.0.0    PnpDevice                           {Get-PnpDevice, Get-PnpDeviceProperty, Enable-PnpDevice, Disable-PnpDevice}
Manifest   2.0.0.0    VpnClient                           {Add-VpnConnection, Set-VpnConnection, Remove-VpnConnection, Get-VpnConnection...}
```

**Comment by gautamdsheth** [comment]
@bfloog , @xaviv - can you please try with the latest nightly build and let us know ?

**Comment by JazBInKC** [comment]
Additionally, Get-PnPFile is doing a file / path not found if the path contains "+".  This must have worked in earlier releases as I'm updating an existing target created with the same code (with paths that contain "+").

I'm on 1.10.24

jbw

**Comment by milanholemans** [comment]
Might be a similar issue like https://github.com/pnp/powershell/issues/1864 .
Haven't tested it yet but seems like a similar issue.

**Comment by gautamdsheth** [comment]
@bfloog / @JazBInKC  - closing this is the same as #1864 , the fix will be available in tomorrow's nightly.
