### ISSUE TITLE
I'm trying to add list items in a simple site.. but keep getting Invalid file name error:

### ISSUE THREAD

**Issue by erwinvanhunen** [pnp/powershell#197]
I'm trying to add list items in a simple site.. but keep getting Invalid file name error:
```
$batch = New-PnPBatch
Add-PnPListItem -List $list -Values @{"Title" ="site1"} -Batch $batch
Add-PnPListItem -List $list -Values @{"Title" ="site2"} -Batch $batch
Add-PnPListItem -List $list -Values @{"Title" ="site3"} -Batch $batch   
$details= Invoke-PnPBatch -Batch $batch -Details

```
results in 

Invalid file name.
The file name you specified could not be used.  It may be the name of an existing file or directory, or you may not have permission to access the file.

I'm using
Manifest   1.2.0      PnP.PowerShell  
Tested with nightly build as well:
Manifest   1.2.7      PnP.PowerShell

Note: it works if I remove the batching.

_Originally posted by @bhishma in https://github.com/pnp/powershell/discussions/195_

**Comment by erwinvanhunen** [comment]
@bhishma: how do you connect, e.g. which way of connecting with Connect-PnPOnline do you use?

**Comment by jansenbe** [comment]
@bhishma: please also share the output from `Get-PnPException` which you can call immediately after the error happens.

**Comment by bhishma** [comment]
@erwinvanhunen, I'm using StoredCredentials to connect Connect-PnPOnline -Url "" -Credential "myaccount"

@jansenbe , When I execute Get-PnPException, it does not return anything.

```
PS C:\Users\testUser> $list=Get-PnPList "SharePoint Sites"
PS C:\Users\testUser> $batch = New-PnPBatch
PS C:\Users\testUser> Add-PnPListItem -List $list -Values @{"Title" ="site1"} -Batch $batch
PS C:\Users\testUser> Add-PnPListItem -List $list -Values @{"Title" ="site2"} -Batch $batch
PS C:\Users\testUser> Invoke-PnPBatch -Batch $batch -Details

ErrorMessage
------------
Invalid file name....
Invalid file name....
Invalid file name....
Invalid file name....


PS C:\Users\testUser> Get-PnPException
PS C:\Users\testUser> Get-Module

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   1.2.7      PnP.PowerShell                      {Add-PnPAlert, Add-PnPApp, Add-PnPApplication... 


PS C:\Users\testUser> $list

Title                   Id                                   Url
-----                   --                                   ---
SharePoint Sites gudiddd-dac2-460c-b67b-90ffbe9bd11b /sites/test/Lists/SharePoint Sites
```

**Comment by erwinvanhunen** [comment]
Trying to eliminate causes, are the items actually being created? Or you just receive the file not found message? Have you tried without the -Details parameter?

**Comment by bhishma** [comment]
They are not created. I tried without -Details as well. Same result.

**Comment by erwinvanhunen** [comment]
The detail lines you see contain more information:

```powershell
$details = Invoke-PnPBatch -Details
$detaiils | select ResponseJson
```

We're interested in seeing the full detail of the ResponseJson.

Another thing: could you try to run the `Invoke-PnPBatch` cmdlet with the `-StopOnException` parameter? It could potentially show more information. 

If neither of these steps above return any data:
Are you familiar with Fiddler? If so, we would like to see a fiddler trace. (https://getfiddler.com). Start fiddler, then launch PowerShell (it's important to do it in that order) . Then execute your code. You'll see requests being executed which end on `/_api/$batch`. We would also be interested in seeing those requests, that is, the response data returned from those requests.

**Comment by bhishma** [comment]
I can see this in Details but Nothing in ResponseJson.
```
ErrorMessage    ResponseCode Request
------------    ------------ -------
File Not Found.          404 https://domain.sharepoint.com/_api/Web/Lists(guid'guid-9140-40f7-a84f-2e77da87e0d5')/AddValidateUpdateItemUsingPath
File Not Found.          404 https://domain.sharepoint.com/_api/Web/Lists(guid'guid-9140-40f7-a84f-2e77da87e0d5')/AddValidateUpdateItemUsingPath
File Not Found.          404 https://domain.sharepoint.com/_api/Web/Lists(guid'guid-9140-40f7-a84f-2e77da87e0d5')/AddValidateUpdateItemUsingPath
File Not Found.          404 https://domain.sharepoint.com/_api/Web/Lists(guid'guid-9140-40f7-a84f-2e77da87e0d5')/AddValidateUpdateItemUsingPath
```
If I use StopOnExecution this is the error:
```
PS C:\Users\testUser> Invoke-PnPBatch $batch -Details -StopOnException
Invoke-PnPBatch : File Not Found.
At line:1 char:1
+ Invoke-PnPBatch $batch -Details -StopOnException
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Invoke-PnPBatch], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,PnP.PowerShell.Commands.Base.InvokeBatch

PS C:\Users\testUser> Get-PnPException
Message          : File Not Found.
Stacktrace       :    at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord()
                      at System.Management.Automation.CommandProcessor.ProcessRecord()
ScriptLineNumber : 1
```
I'm behind corporate proxy, I'm not able to connect to SPO if I let Fiddler change proxy. If I use corporate proxy, Fiddler is not capturing the traffic. I'll try to do this on a computer that's not on proxy.

**Comment by erwinvanhunen** [comment]
okay, the results you see are actualy error reports from the server. And when looking at the URL for each request I see something strange there. The guid of the list is written as `guid'-guid-9140-40f7-etc.`. That's not how it should be written, it should be `guid'9140-40f7-etc`. I'm very confused why that is... 

I'm moving this issue to the Core SDK and we continue in that repo with this issue.
