### ISSUE TITLE
[BUG] Add-PnPGroupMember randomly fails with "User cannot be found"

### ISSUE THREAD

**Issue by iloving** [pnp/powershell#2278]
While running a script that creates a new sharepoint site, invocations to Add-PnPGroupMember will randomly fail with "User cannot be found.".  I am trying to add Azure AD users and groups to a sharepoint group.  I am using the format "`c:0t.c|tenant|<Azure Object GUID>`"

### Expected behavior 
I expect the user or group to be added to the sharepoint group.

### Actual behavior 
Sometimes the call will randomly fail for no obvious reason.

Adding user 'c:0t.c|tenant|_GUID_'
Add-PnPGroupMember: _/PATH/TO/MY/SCRIPT_.ps1:500:9
Line |
 500 |          Add-PnPGroupMember -Group "$groupName" -LoginName "$memberToA …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | User cannot be found.

The error comes up completely randomly, and repeated executions of the script may or may not work fine.

### Steps to reproduce behavior
I have no idea how to reproduce this consistently.  The issue is more likely to appear in the middle of the afternoon for some reason, but that's all I've been able to determine.

### What is the version of the Cmdlet module you are running?
1.10.0

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Linux
- [ X ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by CallumCrowley** [comment]
Please set tracing to "debug" using Set-PnPTraceLog and provide further information. This will allow the community to better understand the issue.

**Comment by iloving** [comment]
Different error this time, and strangely, trace didn't return anything for that cmdlet.  I'm using `Set-PnPTraceLog -On -Level Debug -WriteToConsole`. Am I missing something?

PS $_MYPATH_> ./MasterSiteCreateScript.ps1 -SiteIdentifier ilsatest -SiteTitle "Ilsa Test Site" -SiteType Internal -ProgramCode test -ProgramDesc "Test Program" -DocketNumber 4567 -DocketDesc "Test Docket" -DeleteOldSite
Checking for existing site
Site found.  Deleting.
Waiting 5 seconds cause sharepoint is a nightmare.
Creating Site Ilsa Test Site
pwsh Error: 0 : 2022-08-29 10:40:05.8138        [PnP.Framework] [0]     [Error] ExecuteQuery threw following exception: Microsoft.SharePoint.Client.ServerException: Cannot get site $_MYSITE_.
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServerAsync(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryAsync()
   at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQueryAsync()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQueryAsync()
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, String userAgent)
ServerErrorCode: -1
ServerErrorTypeName: Microsoft.Online.SharePoint.Common.SpoNoSiteException
ServerErrorTraceCorrelationId: 87c35fa0-e038-2000-4c01-249a1330dfb8
ServerErrorValue: 
ServerErrorDetails: 
.       0ms
pwsh Error: 0 : 2022-08-29 10:40:06.0371        [PnP.Framework] [0]     [Error] ExecuteQuery threw following exception: Microsoft.SharePoint.Client.ServerException: Unknown Error
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServerAsync(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryAsync()
   at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQueryAsync()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQueryAsync()
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, String userAgent)
ServerErrorCode: -1
ServerErrorTypeName: Microsoft.SharePoint.Client.UnknownError
ServerErrorTraceCorrelationId: 87c35fa0-d04f-2000-533e-66b556424ac5
ServerErrorValue: 
ServerErrorDetails: 
.       0ms
..True
Site Collection $_MYSITE_ Created Successfully!
Connecting to Site
Setting Site Permissions
Adding member 'c:0t.c|tenant|$_MYGUID_'
Add-PnPGroupMember: $MYPATH/MasterSiteCreateScript.ps1:523:9
Line |
 523 |          Add-PnPGroupMember -Connection $Connection -Group "$groupName …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Object reference not set to an instance of an object.

Write-Error: $_MYPATH_/MasterSiteCreateScript.ps1:307:5
Line |
 307 |      Add-GroupMember -groupName "$groupTitle" -memberToAdd "$group_hig …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Failed.  Trying 9 more times...

**Comment by CallumCrowley** [comment]
Are you deleting a site and then recreating it with the same URL?

**Comment by gautamdsheth** [comment]
Same here as well, will have to move this to discussions since this an issue with the environment or the script itself and not the cmdlet.

As @Studermarc said, deleting and recreating the sites immediately will have an impact on the cmdlet operations.
