### ISSUE TITLE
[BUG] Get-PnPPage not working on a subsite

### ISSUE THREAD

**Issue by zyborc** [pnp/powershell#2328]
### Reporting an Issue 
I am connection with PnP-Powershell to a SharePoint Online Subsite and trying to get a page with Get-PnpPage and it wont find any page.

I am connecting with interactive or useWeblogin because of MFA

### Expected behavior 
Running Get-PnPPage to retrive page data with webparts etc.

### Actual behavior 
The command wont find any page. 

### Steps to reproduce behavior
Connect to a subsite in SharePoint online and try to get Get-PnPPage Home

### What is the version of the Cmdlet module you are running?
1.11.0

### Which operating system/environment are you running PnP PowerShell on?
- [ x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

Error with Export-PnPPage

Message          : Object reference not set to an instance of an object.
Stacktrace       :    at PnP.Framework.Provisioning.ObjectHandlers.Utilities.ClientSidePageContentsHelper.ExtractClientSidePage(Web web, 
                   ProvisioningTemplate template, ProvisioningTemplateCreationInformation creationInfo, PnPMonitoredScope scope, PageToExport page)
                      at PnP.PowerShell.Commands.Provisioning.Tenant.ExportPage.ExtractTemplate(String dirName, String fileName, ExtractConfiguration 
                   configuration)
                      at PnP.PowerShell.Commands.Provisioning.Tenant.ExportPage.ProcessRecord()
                      at System.Management.Automation.CommandProcessor.ProcessRecord()
ScriptLineNumber : 1

**Comment by zyborc** [comment]
I just testet Add-PnPPage on a subsite and it was created on the SiteCollection level. I just connected to the subsite. I even used it with the -Web parameter.

**Comment by zyborc** [comment]
I think i found out that this problem does not have anything to do with the subsite architecture. 
I had two other sitepage libraries from an migration on the side. 
After i moved the pages and deleted the libraries the command works as expected.
