### ISSUE TITLE
[BUG] Get-PnPField not returning site fields

### ISSUE THREAD

**Issue by jsmileyb** [pnp/powershell#300]
### Reporting an Issue
Attempting to view all site fields and fields I created (associated with a custom group) ** Get-PnPField or Get-PnPField -Group "My Custom Group Name Here"

### Expected behavior 
Expected list of fields associated with my site

### Actual behavior 
Unless I explicitly attach -Identity to the call, I receive the below error:
**Get-PnPField : Input string was not in a correct format.
At line:1 char:1
+ Get-PnPField
+ ~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPField], ServerException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Fields.GetField**

### Steps to reproduce behavior
Connect-PnPOnline -Url $Site -Credentials (Get-Credentials)
Get-PnPField

....that's about it. 

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

1.3.0

### Which operating system/environment are you running PnP PowerShell on?
- [X ] Windows

**Comment by jsmileyb** [comment]
I'm now getting the same error with Add-PnPFieldFromXml. All from scripts that have been working for weeks :: even ran this morning without error/issue. Now receiving "_Input string was not in a correct format_" for both. 

Is this related?

Add-PnPFieldFromXml : Input string was not in a correct format.
At line:1 char:1
+ Add-PnPFieldFromXml -FieldXml $fieldXml
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Add-PnPFieldFromXml], ServerException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Fields.AddFieldFromXml

**Comment by LeonArmston** [comment]
Please can you run **Get-PnPException** immediately after the error occurs and post the output in here?

Thanks

**Comment by jsmileyb** [comment]
Message          : Input string was not in a correct format.
Stacktrace       :    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
                      at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
                      at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__53.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__39.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__65.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__28.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__6.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, String userAgent)
                      at PnP.PowerShell.Commands.Fields.GetField.ExecuteCmdlet()
                      at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord()
ScriptLineNumber : 1

**Comment by jsmileyb** [comment]
This is the error when using a Group filter: Get-PnPField -Group "My Custom Group Test"

Message          : Input string was not in a correct format.
Stacktrace       :    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
                      at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
                      at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__53.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__39.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__65.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__28.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__6.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, String userAgent)
                      at PnP.PowerShell.Commands.Fields.GetField.ExecuteCmdlet()
                      at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord()
ScriptLineNumber : 1

**Comment by veronicageek** [comment]
That's odd. I don't have any issues on my end with 1.3.0 (Windows/MacOS)

![image](https://user-images.githubusercontent.com/25181757/108599291-3cef6300-7388-11eb-9467-99b30d72d9d5.png)

**Comment by jsmileyb** [comment]
Indeed. I've tried the command on 4+ sites this morning without issue. I have no idea what was going on last week.

**Comment by jsmileyb** [comment]
Can no longer recreate this issue.
