### ISSUE TITLE
[BUG] Copy-PnPFile won't copy page from one sitecollection to another

### ISSUE THREAD

**Issue by kai-noventum** [pnp/powershell#3211]
### Reporting an Issue
I used to have a script that creates new sharepoint sites and copies example pages from one site collection to the fresh one.
It stopped working.

Command basically is:
Copy-PnPFile -SourceUrl "/SitePages/Bereich/Start.aspx" -TargetUrl "/sites/KaisPersoenlicheTestseite/SitePages" -Force -Connection $templateConnection

$templateConnections contains the -ReturnConnection from the Connect-PnPOnline (the Source Site Connection).

### Expected behavior 
The ASPX-File "Start.aspx" from the template sitecollection should be copied to "https://[tenant].sharepoint.com/sites/KaisPersoenlicheTestseite/SitePages/".

### Actual behavior 
Unzulässiger Zahlenwert.

Ein Nummernfeld enthält unzulässige Daten. Überprüfen Sie die Eingabe, und versuchen Sie es erneut. CallStack --    at Microsoft.SharePoint.SPGlobal.HandleComException(COMException comEx)
   at Microsoft.SharePoint.Library.SPRequest.CreateOrUpdateFileAndItem(String bstrUrl, String bstrWebRelativeUrl, Guid& docId, Object punkDoc, Int32 docLength, Int32 exists, String bstrCreatedBy, String bstrModifiedBy, Int32 iCreatedByID, Int32 iModifiedByID, Int32 iVersion, Object varTimeCreated, Object varTimeLastModified, Object varProperties, String checkInComment, Int32 docLibRowID, String bstrListName, Int32 bNoExecute, SPFileSaveParams sfsp, Int32 bSkipModerateStatusCheck, UInt32& pdwVirusCheckStatus, String& pVirusCheckMessage, Object& pvarMergedProperties)
   at Microsoft.SharePoint.Deployment.FileSerializer.CreateOrUpdateFileWithGuid(Stream spstm, SPLoggerObject loggerObject, SPWeb web, Guid fileId, SPResourcePath filePath, String fileValue, Int64 bytesInAzure, String quickXorHash, Int32 authorId, String authorLoginName, Int32& editorId, String editorLoginName, String checkinComment, DateTime& timeCreated, DateTime& timeLastModified, MetaInfoHandler metaInfo, Int64 length, Int32 iVersion, Boolean isFirstVersion, Nullable`1 isLastVersion, SPImportSettings settings, Int32 listItemId, String listInternalName, Boolean hasNoExecuteFlag, ImportObjectManager objectManager, DecryptionInfo decryptionInfo, Nullable`1 preserveExistingOnConflict, Nullable`1 createAntlerFile, Guid parentId, Object& propertyArray, Object& mergedMetaProperties, Boolean createStubFileOnly)

Object reference not set to an instance of an object. CallStack --    at Microsoft.SharePoint.Deployment.ListItemVersionSerializer.AddListItemVersion(SPWeb web, SPListItem listItem, SPLoggerObject loggerObject, Guid newId, Boolean editHistory, Boolean existsInDb, Boolean isFirst, Boolean isLast, Boolean isDocLib, StreamingContext context, XmlElement listItemData, SerializationInfoHelper listItemInfoHelper, XmlDocument listItemVersionsXml, SPResourcePath& listItemServerRelativeUrl, ISurrogateSelector selector, LoggerStatistics stats, Guid docId)
   at Microsoft.SharePoint.Deployment.ListItemSerializer.UpdateListItemVersionData(SerializationInfoHelper infoHelper, SPWeb web, SPListItem& listItem, Guid newId, Boolean existsInDb, Boolean isDocLib, SPResourcePath& listItemServerRelativePath, StreamingContext context, ISurrogateSelector selector)
   at Microsoft.SharePoint.Deployment.ListItemSerializer.SetObjectData(Object obj, SerializationInfo info, StreamingContext context, ISurrogateSelector selector)
   at Microsoft.SharePoint.Deployment.XmlFormatter.CallSetObjectData(Object obj, SerializationInfo objectData, ISerializationSurrogate surrogate, ISurrogateSelector selector)

### Steps to reproduce behavior
1. Create a folder in the source site collections "SitePages"-library and put a site in there (e.g. Home.aspx).
2. Create a target SharePoint communication site.
3. Run the script:
$templateConnection = Connect-PnpOnline -Url https://[tenant].sharepoint.com/sites/TemplateCollection -ReturnConnection
Copy-PnPFile -SourceUrl "/SitePages/[folder]/Start.aspx" -TargetUrl "/sites/KaisPersoenlicheTestseite/SitePages" -Force 
Connection $templateConnection
4. Error Pops up (two returns)

### What is the version of the Cmdlet module you are running?
2.1.1 (PnP.PowerShell) on PowerShell 7.3.4

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Hi @kai-noventum , this is not supported by SharePoint APIs themselves, so we can't do anything here about it. Please raise a feature request with Microsoft about this.

What you can do, for now, is export the page using `Export-PnPPPage` cmdlet and then apply the template in another site collection.

Will have to close the issue.
