### ISSUE TITLE
[BUG]New-PnPSite: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Rbubbles** [pnp/powershell#3273]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.

### Reporting an Issue or Missing Feature
New-PnPSite gives the error : **New-PnPSite: Object reference not set to an instance of an object.**

### Expected behavior 
Expected behavior is to create a new TeamSite 

### Actual behavior 
**Error from PS:**
![image](https://github.com/pnp/powershell/assets/100543772/e82464bb-f61c-4190-9d10-d53a2e9305f4)
 **Error from Azure function:**
 
 Exception             : 
    Type       : System.NullReferenceException
    TargetSite : 
        Name          : ExecuteCmdlet
        DeclaringType : PnP.PowerShell.Commands.NewSite
        MemberType    : Method
        Module        : PnP.PowerShell.dll
    Message    : Object reference not set to an instance of an object.
    Data       : System.Collections.ListDictionaryInternal
    Source     : PnP.PowerShell
    HResult    : -2147467261
    StackTrace : 
   at PnP.PowerShell.Commands.NewSite.ExecuteCmdlet() in c:\build\src\Commands\Admin\NewSite.cs:line 133
   at PnP.PowerShell.Commands.Base.PnPConnectedCmdlet.ProcessRecord() in c:\build\src\Commands\Base\PnPConnectedCmdlet.cs:line 53
CategoryInfo          : WriteError: (:) [New-PnPSite], NullReferenceException

### Steps to reproduce behavior
$Connection = Connect-PnPOnline -Url $Url -ClientId $app.ClientId -Thumbprint $app.Thumbprint -Tenant $app.Tenant -ReturnConnection -ErrorAction Stop;
New-PnPSite -Type TeamSite -Title "PNP2.2" -Alias "Bla bla bla" -Connection $Connection -Wait -ErrorAction Stop;

### What is the version of the Cmdlet module you are running?
![image](https://github.com/pnp/powershell/assets/100543772/c7f91d94-5f38-43c5-9c9a-e3d5a23d81ea)

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [X] Azure Functions
- [ ] Other : please specify

**Comment by Rbubbles** [comment]
Hi @gautamdsheth , with or without the -Owners parameter. The same error occurs.

**Comment by Rbubbles** [comment]
Here is the full cmdlet for reference:
New-PnPSite -PreferredDataLocation AUS -Description "bla bla bal" -Type TeamSite -HubSiteId f2XXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXX -Title "TestSitePNP" -Alias "TestSitePNP" -Owners user1@MS.onmicrosoft.com -Connection $Connection -Wait -ErrorAction Stop

**Comment by svermaak** [comment]
![image](https://github.com/pnp/powershell/assets/12259728/069a1245-bc6b-44d9-8336-58384008cc7d)

**Comment by svermaak** [comment]
Without connection (as in connecting without -ReturnConnection) there's no issue.

It seems like the connection returned by -ReturnConnection "has no context"

![image](https://github.com/pnp/powershell/assets/12259728/35a0d38b-308f-4764-b69c-237249df41fb)

**Comment by gautamdsheth** [comment]
@Rbubbles - is it the same with you as well when you remove the `-Connection` parameter ?

**Comment by Rbubbles** [comment]
@gautamdsheth , yes it is the same for me

**Comment by gautamdsheth** [comment]
Have managed to figure it out and fix it. 
Will be available in tomorrow's nightly build.

Thanks for reporting, do let me know if the issue still persists

**Comment by svermaak** [comment]
Excellent! Will give it a go

**Comment by svermaak** [comment]
It has context issue 
![Uploading image.png…]()

**Comment by svermaak** [comment]
![image](https://github.com/pnp/powershell/assets/12259728/b4d497fa-3ca5-4783-a003-98ea801c82eb)

**Comment by mblennegard** [comment]
@gautamdsheth This seems to still be an issue. Can the bug be re-opened?

**Comment by mblennegard** [comment]
@svermaak  I can confirm that this now works as expected (according to the documentation) in the nighly release build PnP.PowerShell 2.2.61.
