### ISSUE TITLE
[BUG] Add-PnPListItem & Batching doesn't work with a French created site collection

### ISSUE THREAD

**Issue by hervedorierai3** [pnp/powershell#3365]
### Reporting an Issue or Missing Feature
I have to import data from CSV file to a list. I use Add-PnPListItem with -Batch option to improve the import time.

I developped my script in a English site collection : no problem at all.
I tested my script in a French site collection : the Add-PnPListItem fails with error "Object reference not set to an instance of an object."
If I remove the -Batch option, the items are created in the list (but it's very, very, very long).

I'm sure that it's not a permission issue because the script delete all item in the list (Remove-PnPListItem -Batch).
I'm connected with an Azure AD Application (Register-PnPAzureADApp -ApplicationName "MyBatchApp" -Tenant xxxx.onmicrosoft.com  -SharePointApplicationPermissions Sites.Manage.All -Password (ConvertTo-SecureString -String "xxxxxxx" -AsPlainText -Force) -DeviceLogin  )

### Expected behavior 
Would expect the item is successfully added to the list 😊

### Actual behavior 
Add-PnPListItem fails with error "Object reference not set to an instance of an object."

![image](https://github.com/pnp/powershell/assets/68116737/1c1ba761-ab1d-456b-a020-a2763cd95d87)

### Steps to reproduce behavior
- Create a "Communication" site collection with "French" as language.
- Create a simple list (only the Title column).
- Connect to the site collection with Certificate (Connect-PnPOnline -Url $siteurl -ClientId $application_clientid -Tenant $tenant_name -Thumbprint $certificate_thumbprint)
- Try to add an item to the list with Add-PnPListItem and -Batch option ==> Fails 😨
- Try to add an item to the list with Add-PnPListItem but without -Batch option ==> Success 😊

### What is the version of the Cmdlet module you are running?
2.2.55 nigthly

### Which operating system/environment are you running PnP PowerShell on?
- [ x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
@hervedorierai3 , please try to provide minimal steps to reproduce this issue.

Would suggest that you try it by adding a single list item via batch and also via CSOM and let us know.

**Comment by hervedorierai3** [comment]
Added sample code.
Added mention that with interactive connection there is no problem.

**Comment by hervedorierai3** [comment]
@gautamdsheth : 
Added sample code.
Added mention that with interactive connection there is no problem.

**Comment by stevebeauge** [comment]
I have a similar issue when running `New-PnPSite`. If I use the *ambiant* connection, no issue. But If I use a *returned* connection, it fails with the exact same error message.

Working:
````powershell
Import-Module PnP.Powershell

$tenant = "myCorporate"
$sitePrefix = "Testing"
$timestamp = (Get-Date -Format s) -replace "[\:|T]", "-"
$siteName = $sitePrefix + " " + $timestamp
$alias = $siteName.Replace(" ", "-")
$siteUrl = "https://$tenant.sharepoint.com/sites/$alias"
Connect-PnPOnline -Url "https://$tenant.sharepoint.com" -Interactive 

$myLogin = Get-PnPProperty -ClientObject (Get-PnPContext).Web.CurrentUser -Property Loginname 

# & "$PSScriptRoot\Run-DeploySiteScriptsAndSiteDesigns.ps1"

New-PnPSite -Type TeamSite `
    -Title $siteName  `
    -Alias $alias  `
    -Wait  `
    -Lcid 1036 `
    -Owner $myLogin 
````

Non working:

````powershell
Import-Module PnP.Powershell

$tenant = "myCorporate"
$sitePrefix = "Testing"
$timestamp = (Get-Date -Format s) -replace "[\:|T]", "-"
$siteName = $sitePrefix + " " + $timestamp
$alias = $siteName.Replace(" ", "-")
$siteUrl = "https://$tenant.sharepoint.com/sites/$alias"
if (-not $adminCnx) {
    $adminCnx = Connect-PnPOnline -Url "https://$tenant.sharepoint.com" -Interactive -ReturnConnection
}

$myLogin = Get-PnPProperty -ClientObject $admincnx.Context.Web.CurrentUser -Property Loginname -Connection $admincnx

# & "$PSScriptRoot\Run-DeploySiteScriptsAndSiteDesigns.ps1"

New-PnPSite -Type TeamSite `
    -Title $siteName  `
    -Alias $alias  `
    -Wait  `
    -Lcid 1036 `
    -Owner $myLogin  `
    -Connection $adminCnx

````

Strangely, if I have an ambient connection, everything is OK even with passing connection parameter. I guess there's somewhere in the pnp powershell code a reference to the ambient connection instead of the connection from parameters.

If it can help, the stack trace (grabbed using `$Error[0].Exception.toString()`) is:

````plain
System.Management.Automation.PSInvalidOperationException: File Not Found.
   at PnP.PowerShell.Commands.Base.PnPConnectedCmdlet.ProcessRecord() in c:\build\src\Commands\Base\PnPConnectedCmdlet.cs:line 101
   at System.Management.Automation.CommandProcessor.ProcessRecord()
````

Which correspond to this *error shallowing* code: https://github.com/pnp/powershell/blob/b6c927e6d24d796e32377f5e232c73c12eeec5d6/src/Commands/Base/PnPConnectedCmdlet.cs#L99-L102

**Comment by hervedorierai3** [comment]
@gautamdsheth could you remove the 'needmoreinformation' tag please ?

**Comment by reshmee011** [comment]
@hervedorierai3 : I understand it's a 3 year old issue already, can you still reproduce the issue with the latest build?

**Comment by stevebeauge** [comment]
This repro is working as expected now:

```
Import-Module PnP.Powershell

$tenant = "myCorp"
$sitePrefix = "Testing"
$timestamp = (Get-Date -Format s) -replace "[\:|T]", "-"
$siteName = $sitePrefix + " " + $timestamp
$alias = $siteName.Replace(" ", "-")
$siteUrl = "https://$tenant.sharepoint.com/sites/$alias"
if (-not $adminCnx) {
    $adminCnx = Connect-PnPOnline -Url "https://$tenant.sharepoint.com" -Interactive -ReturnConnection
}

$myLogin = Get-PnPProperty -ClientObject $admincnx.Context.Web.CurrentUser -Property Loginname -Connection $admincnx

# & "$PSScriptRoot\Run-DeploySiteScriptsAndSiteDesigns.ps1"

New-PnPSite -Type TeamSite `
    -Title $siteName  `
    -Alias $alias  `
    -Wait  `
    -Lcid 1036 `
    -Owner $myLogin.Replace("i:0#.f|membership|", "")  `
    -Connection $adminCnx

```

**Comment by reshmee011** [comment]
@stevebeauge : Amazing news, probably it might either been fixed or something changed in the back end API.
