### ISSUE TITLE
[BUG] - Get-PnPPageComponent error with Nordic chars ø,æ,å

### ISSUE THREAD

**Issue by kasperbolarsen** [pnp/powershell#3401]
### Reporting an Issue or Missing Feature
I am extrating the web parts from a number of pages in the SitePages library on a site collection using Get-PnPPageComponent. It works just fine for most pages, however pages where the name (FileLeafRef) contains one of the Nordic chars ø,æ,å 

### Expected behavior 
Please describe what output you expect to see from the PnP PowerShell Cmdlets
A list of web parts :-)

### Actual behavior 

I get this exception:
get-PnPException                                                 

Message          : 'c' is invalid after a value. Expected either ',', '}', or ']'. Path: $ | LineNumber: 0 | BytePositionInLine: 857.   
Stacktrace       :    at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
                      at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
                      at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
                      at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
                      at PnP.Core.Model.SharePoint.PageWebPart.FromHtml(IElement element)
                      at PnP.Core.Model.SharePoint.Page.LoadFromHtml(String html, String pageHeaderHtml)
                      at PnP.Core.Model.SharePoint.Page.LoadPageAsync(IList pagesLibrary, IListItem item)
                      at PnP.Core.Model.SharePoint.Page.LoadPagesAsync(PnPContext context, String pageName)
                      at PnP.Core.Model.SharePoint.Web.GetPagesAsync(String pageName)
                      at PnP.Core.Model.SharePoint.Web.GetPages(String pageName)
                      at PnP.PowerShell.Commands.Base.PipeBinds.PagePipeBind.GetPage(PnPConnection connection) in c:\build\src\Commands\Base\PipeBinds\PagePipeBind.cs:line 64
                      at PnP.PowerShell.Commands.Pages.GetPageComponent.ExecuteCmdlet() in c:\build\src\Commands\Pages\GetPageComponent.cs:line 24
                      at PnP.PowerShell.Commands.Base.PnPConnectedCmdlet.ProcessRecord() in c:\build\src\Commands\Base\PnPConnectedCmdlet.cs:line 53
ScriptLineNumber : 28

### Steps to reproduce behavior
add a page by the name "Testområde" to the SitePages
Iterate the pages and:

$file = $page.FieldValues["FileLeafRef"] 
Write-Host " Processing Page $($file)" -ForegroundColor Cyan
try
{
    $components = Get-PnPPageComponent -Page $file -Connection $localconnection -ErrorAction Stop
}
catch
{
    Write-Host "    Error getting page components" -ForegroundColor Red
}

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)
2.2.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Have you tried encoding the page name ? Might be it will work

**Comment by kasperbolarsen** [comment]
Hi Gautam, do you mean like this : 
$file = [System.Web.HttpUtility]::UrlEncode($file) 

If changes the exception to Page 'Testomr%c3%a5de.aspx' does not exist :-(

**Comment by NishkalankBezawada** [comment]
Hey @kasperbolarsen 

I tried to replicate the issue, with below sample code, but of no luck.

![image](https://github.com/pnp/powershell/assets/47456098/ece38499-aed5-4e82-bff5-41495f7714f5)

And below is the result

![image](https://github.com/pnp/powershell/assets/47456098/bb944ebe-90a9-4afd-91b5-11ff2f20ee3c)

I havent got any error though. 

Here are the versions in my machine

![image](https://github.com/pnp/powershell/assets/47456098/89b0762f-0efa-4e89-985b-77f9ce922f52)


Thanks,
Nishkalank

**Comment by veronicageek** [comment]
Thanks @NishkalankBezawada for testing.
@kasperbolarsen - Do you still have the issue? If yes, can you try on a newly created page with your specific characters.

**Comment by kasperbolarsen** [comment]
I do still have the issue, and will provide a script showing the issue.  Should have done that long ago but other issues got priority

**Comment by kasperbolarsen** [comment]
I have tried to verified the issue and tested various options. The is related to one of the web parts on the page and has nothing to do with the URL of the page.
Case can be closed
