### ISSUE TITLE
Set-PnPListItemPermission : Permission level not found

### ISSUE THREAD

**Issue by kamco11** [pnp/powershell#374]
Set-PnPListItemPermission -List 'Documents' -Identity $id -User '$user' -AddRole 'Edit'

```
powershell.exe Error: 0 : 2021-03-04 09:04:09.1783      [PnP.Framework] [0]     [Error] ExecuteQuery threw following exception: Microsoft.SharePoint.Client.ServerException: Permission level not found.
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__65.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__6.MoveNext()
ServerErrorCode: -2146232832
ServerErrorTypeName: Microsoft.SharePoint.SPException
ServerErrorTraceCorrelationId: 0de7b09f-701b-b000-e898-ae226f9756be
ServerErrorValue:
ServerErrorDetails:
.       0ms
Set-PnPListItemPermission : Permission level not found.
At line:1 char:1
+ Set-PnPListItemPermission -List 'Documents' -Identity $id -User '$use ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Set-PnPListItemPermission], ServerException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Lists.SetListItemPermission
```

### What is the version of the Cmdlet module you are running?
1.3.18

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@kamco11 - Are you sure the site you're connected to has this permission level? You can see that by running `Get-PnPRoleDefinition`.

I don't see this issue on my side:

![image](https://user-images.githubusercontent.com/25181757/110007661-d583cc80-7d12-11eb-8ab2-96b2248611ee.png)

**Comment by kamco11** [comment]
> It could be that the language could be different for you.
> For example, `Edit` translates to `Bearbeiten` in German.
> Could you try with the translated word for `Edit`, ie. translate Edit to your local language and check ?
> You can find that in your site collection here - `<site-url>/_layouts/15/role.aspx` in your local language.

Sorry, I had no time to test it. I'll look on it as soon as possible. Thanks.

**Comment by veronicageek** [comment]
@kamco11 - I'll close this issue for now, please re-open if you're still facing an issue.

**Comment by kamco11** [comment]
Correct guys. There was a problem with translation.
I set language to English and it works.
Thanks.
