### ISSUE TITLE
[BUG] Get-PnPSharePointAddIn does not works : The requested operation requires an element of type 'String', but the target element has type 'Null'.

### ISSUE THREAD

**Issue by stevebeauge** [pnp/powershell#3776]
### Reporting an Issue or Missing Feature
Calling `Get-PnPSharePointAddIn` fails with some obscure error message

### Expected behavior 
The command should return the list of installed addins

### Actual behavior 
The command fails:

>  Get-PnPSharePointAddIn
>     |  ~~~~~~~~~~~~~~~~~~~~~~
 >    | The requested operation requires an element of type 'String', but the target element has type 'Null'.

### Steps to reproduce behavior
Save in a file the following script and run it:

````powershell
Import-Module PnP.PowerShell

Connect-PnPOnline -Url "https://tenant.sharepoint.com/sites/somecollection" -Interactive

Set-PnPTraceLog -On -WriteToConsole -Level Debug -LogFile "$PSScriptRoot\log.txt"

Get-PnPSharePointAddIn
````

FYI, the `log.txt` file is created but remains empty.

Trying to understand what's wrong, I can get some tip using these code:

````powershell
Get-PnPSharePointAddIn
$err = $error[0]
$err.Exception | fl
````

Which returns:

````text
ErrorRecord    : The requested operation requires an element of type 'String', but the target element has type 'Null'.
TargetSite     : Void ProcessRecord()
Message        : The requested operation requires an element of type 'String', but the target element has type 'Null'.
Data           : {}
InnerException : 
HelpLink       : 
Source         : PnP.PowerShell
HResult        : -2146233079
StackTrace     :    at PnP.PowerShell.Commands.Base.PnPConnectedCmdlet.ProcessRecord() in c:\build\src\Commands\Base\PnPConnectedCmdlet.cs:line 101
                    at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord() in c:\build\src\Commands\Base\PnPSharePointCmdlet.cs:line 120
                    at System.Management.Automation.CommandProcessor.ProcessRecord()
````

### What is the version of the Cmdlet module you are running?
PnP.Powershell : 2.2.0

````
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
````

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by stevebeauge** [comment]
Side note : the actual exception seems to be shallowed by this code:

https://github.com/pnp/powershell/blob/c42a224c5252159fde054df1da36268324a9b4e7/src/Commands/Base/PnPConnectedCmdlet.cs#L98-L102

Maybe you should keep in some way the actual exception and not only its error message?

**Comment by jackpoz** [comment]
you can get the actual exception if you pass -ErrorAction:Stop to the cmdlet

**Comment by stevebeauge** [comment]
Fair

We can close the issue.

Maybe there was something messed with an older version of the csom.

Thanks
