### ISSUE TITLE
[BUG] New-PnPAzureCertificate: Object reference not set to an instance of an object with Powershell 7.4.1

### ISSUE THREAD

**Issue by OASISfr** [pnp/powershell#3827]
**PnP.Powershell version :** 2.3.0 / 2.4.0
**OS :** Windows 11
**Powershell version :** 7.4.1

**Reporting Issue :**

New-PnPAzureCertificate -OutPfx pnp.pfx -OutCert pnp.cer -CertificatePassword (ConvertTo-SecureString -String "pass@word1" -AsPlainText -Force)

Generate an error : Object reference not set to an instance of an object.

Commandlet is operational with Powershell 7.4.0

**Get-Error :**

Exception             :
    Type       : System.NullReferenceException
    TargetSite :
        Name          : WriteAzureCertificateOutput
        DeclaringType : PnP.PowerShell.Commands.Base.GetPnPAdalCertificate
        MemberType    : Method
        Module        : PnP.PowerShell.dll
    Message    : Object reference not set to an instance of an object.
    Source     : PnP.PowerShell
    HResult    : -2147467261
    StackTrace :
   at PnP.PowerShell.Commands.Base.GetPnPAdalCertificate.WriteAzureCertificateOutput(PSCmdlet cmdlet, X509Certificate2 certificate, SecureString password) in
c:\build\src\Commands\Base\GetAzureCertificate.cs:line 82
   at PnP.PowerShell.Commands.Base.NewPnPAdalCertificate.ProcessRecord() in c:\build\src\Commands\Base\NewAzureCertificate.cs:line 104
   at System.Management.Automation.CommandProcessor.ProcessRecord()
CategoryInfo          : NotSpecified: (:) [New-PnPAzureCertificate], NullReferenceException
FullyQualifiedErrorId : System.NullReferenceException,PnP.PowerShell.Commands.Base.NewPnPAdalCertificate
InvocationInfo        :
    MyCommand        : New-PnPAzureCertificate
    ScriptLineNumber : 1
    OffsetInLine     : 2
    HistoryId        : 4
    Line             :  New-PnPAzureCertificate -OutPfx pnp.pfx -OutCert pnp.cer -CertificatePassword (ConvertTo-SecureString -String "pass@word1" -AsPlainText -Force)
    Statement        : New-PnPAzureCertificate -OutPfx pnp.pfx -OutCert pnp.cer -CertificatePassword (ConvertTo-SecureString -String "pass@word1" -AsPlainText -Force)
    PositionMessage  : At line:1 char:2
                       +  New-PnPAzureCertificate -OutPfx pnp.pfx -OutCert pnp.cer -Certificat …
                       +  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : New-PnPAzureCertificate
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1

**Comment by jackpoz** [comment]
Cannot reproduce the issue using v2.4.8 on Windows 10
![image](https://github.com/pnp/powershell/assets/1153754/f7d39c4b-1f57-47a7-a14f-6b50355f568a)

Did the command create the pfx and cer files ? According to the stacktrace you posted, it failed when showing the certificate in the console but after it got created.
