### ISSUE TITLE
[BUG] New-PnPPlannerPlan fails with unauthorized access using a Service Principal

### ISSUE THREAD

**Issue by StevieBleeds** [pnp/powershell#401]
### Notice
I'm using version 1.3.0 of PnP.PowerShell in Azure Automation with a Service Principal and I keep getting this error when trying to create a new plan in Planner.

### Actual behavior 

```
Message          : <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" 
                   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
                   <html xmlns="http://www.w3.org/1999/xhtml">
                   <head>
                   <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
                   <title>401 - Unauthorized: Access is denied due to invalid credentials.</title>
                   <style type="text/css">
                   <!--
                   body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
                   fieldset{padding:0 15px 10px 15px;} 
                   h1{font-size:2.4em;margin:0;color:#FFF;}
                   h2{font-size:1.7em;margin:0;color:#CC0000;} 
                   h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
                   #header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, 
                   sans-serif;color:#FFF;
                   background-color:#555555;}
                   #content{margin:0 0 0 2%;position:relative;}
                   .content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
                   -->
                   </style>
                   </head>
                   <body>
                   <div id="header"><h1>Server Error</h1></div>
                   <div id="content">
                    <div class="content-container"><fieldset>
                     <h2>401 - Unauthorized: Access is denied due to invalid credentials.</h2>
                     <h3>You do not have permission to view this directory or page using the credentials that you 
                   supplied.</h3>
                    </fieldset></div>
                   </div>
                   </body>
                   </html>
                   
Stacktrace       :    at PnP.PowerShell.Commands.Base.BasePSCmdlet.ProcessRecord()
                      at System.Management.Automation.CommandProcessor.ProcessRecord()
ScriptLineNumber : 11
InvocationInfo   : System.Management.Automation.InvocationInfo
Exception        : System.Management.Automation.PSInvalidOperationException: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 
                   1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
                   <html xmlns="http://www.w3.org/1999/xhtml">
                   <head>
                   <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
                   <title>401 - Unauthorized: Access is denied due to invalid credentials.</title>
                   <style type="text/css">
                   <!--
                   body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
                   fieldset{padding:0 15px 10px 15px;} 
                   h1{font-size:2.4em;margin:0;color:#FFF;}
                   h2{font-size:1.7em;margin:0;color:#CC0000;} 
                   h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
                   #header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, 
                   sans-serif;color:#FFF;
                   background-color:#555555;}
                   #content{margin:0 0 0 2%;position:relative;}
                   .content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
                   -->
                   </style>
                   </head>
                   <body>
                   <div id="header"><h1>Server Error</h1></div>
                   <div id="content">
                    <div class="content-container"><fieldset>
                     <h2>401 - Unauthorized: Access is denied due to invalid credentials.</h2>
                     <h3>You do not have permission to view this directory or page using the credentials that you 
                   supplied.</h3>
                    </fieldset></div>
                   </div>
                   </body>
                   </html>
                   
                      at PnP.PowerShell.Commands.Base.BasePSCmdlet.ProcessRecord()
                      at System.Management.Automation.CommandProcessor.ProcessRecord()
CorrelationId    : 
TimeStampUtc     : 1/1/0001 12:00:00 AM
```

### Steps to reproduce behavior
New-PnPPlannerPlan -Group $GroupId -Title "Test Plan"

### What is the version of the Cmdlet module you are running?
PnP.PowerShell 1.3.0

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [x] Other : please specify (Azure Runbook)

**Comment by StevieBleeds** [comment]
Hey there, I'm using

`Connect-PnPOnline -Url $siteUrl -ClientId $appId -Thumbprint $appThumbprint -Tenant $appAdTenant`

**Comment by gautamdsheth** [comment]
It could be that your Azure AD application has Application permissions for `Group.ReadWrite.All` which is not supported for creating planner plan. Check reference here - https://docs.microsoft.com/en-us/graph/api/planner-post-plans?view=graph-rest-1.0&tabs=http

If that's the case, could you change it delegated permissions and give it a try ?

**Comment by StevieBleeds** [comment]
I've updated to 1.4.0 and changed the permissions to delegated and it's throwing the same error sadly.

**Comment by gautamdsheth** [comment]
For the same Azure AD app, can you try it as below:

```
$creds = Get-Credentials

Connect-PnPOnline -Url "<url>" -Credentials $creds -ClientId "<your-client-id>"
```

or 

```
$creds = Get-Credentials

Connect-PnPOnline -Url "<url>" -Interactive -ClientId "<your-client-id>"
```
and then create the plan ?

**Comment by StevieBleeds** [comment]
It works when using just the -Interactive parameter, but not with the -ClientID parameter.

When I tried using the second method you mentioned, it wouldn't let me authenticate against the service principal.

**Comment by MarekHalfar** [comment]
Any update on this one?

In the meantime I have a non-interactive workaround...First getting the delegated permissions access token directly by doing REST call to https://login.microsoftonline.com/hella.onmicrosoft.com/oauth2/v2.0/token. Then passing it to Connect-PnpOnline in -AccessToken parameter. With such connection it works.
