### ISSUE TITLE
[BUG] Remove-PnPListItem: Property Id was not yet loaded

### ISSUE THREAD

**Issue by seriavio** [pnp/powershell#4129]
### Reporting an Issue or Missing Feature
I'm experiencing sporadic issues with Remove-PnPListItem cmdlet (In scope of a big custom PS Module as follows: `Remove-PnPListItem -List $script:ListName -Identity $Id -Batch $Script:UpdateBatch`) in one of my scheduled scripts, where it produces an error message saying `Property Id was not yet loaded`.

What's strange is that this script is scheduled to run daily and is written in a way that if it fails to delete something from the list today, it will try to delete it again tomorrow. And I've seen it multiple times already where it was failing to delete one or more items from the list and eventually it was succeeding with removal on the next day. Initially, I thought it could have been an issue in the older module version (1.12) so I updated it to the latest one (2.5.0) and recently got this one again (once) but it worked fine next day.

### Expected behavior 
The cmdlet should not throw an exception

### Actual behavior 
Sometimes, the cmdlet produces an exception as follows:
```
PSMessageDetails      : 
Exception             : System.Management.Automation.PSInvalidOperationException: Property Id was not yet loaded
                           at PnP.PowerShell.Commands.Base.PnPConnectedCmdlet.ProcessRecord() in c:\build\src\Commands\Base\PnPConnectedCmdlet.cs:line 101
                           at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord() in c:\build\src\Commands\Base\PnPSharePointCmdlet.cs:line 131
                           at System.Management.Automation.CommandProcessor.ProcessRecord()
TargetObject          : 
CategoryInfo          : InvalidOperation: (:) [Remove-PnPListItem], PSInvalidOperationException
FullyQualifiedErrorId : InvalidOperation,PnP.PowerShell.Commands.Lists.RemoveListItem
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : <REDACTED - leads to a line in a custom module that contains Remove-PnPListItem>
PipelineIterationInfo : {}
```

### Steps to reproduce behavior
`Remove-PnPListItem -List $script:ListName -Identity $Id -Batch $Script:UpdateBatch`, where `$Id` is taken from an object that was returned by `Get-PnPListItem`

### What is the version of the Cmdlet module you are running?
2.5.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by jackpoz** [comment]
Does the `$Id` parameter have a valid value at that point ? Just to be sure the exception is not happening when reading the `$Id` returned by `Get-PnPListItem` .

If you pass `-ErrorAction:Stop` as additional parameter to `Remove-PnPListItem` , it will show the actual callstack instead of the generic `PnP.PowerShell.Commands.Base.PnPConnectedCmdlet.ProcessRecord()` one.

**Comment by seriavio** [comment]
> Does the `$Id` parameter have a valid value at that point ? Just to be sure the exception is not happening when reading the `$Id` returned by `Get-PnPListItem` .
> 
Unfortunately, currently I'm not checking the presence of the value in `$Id` assuming that each List item has one.

> If you pass `-ErrorAction:Stop` as additional parameter to `Remove-PnPListItem` , it will show the actual callstack instead of the generic `PnP.PowerShell.Commands.Base.PnPConnectedCmdlet.ProcessRecord()` one.
 I'll update the code for Remove-PnPListItem to see if we can pull something additional out of it.

Do I understand it correctly that it seems like the value for the Id property of the ListItem may not be populated yet (as it is being done asynchronously under the hood) by the time it is passed into Remove-PnPListItem? If so, what's the best way to make sure that the value is ready? Shall I just try to parse it as integer when saving it into `$Id` or is there a better way? If I'll update the script to log the value, would it force the result to be loaded?

**Comment by gautamdsheth** [comment]
Moving this to a discussion as it seems to be an issue with the custom script and not the cmdlet itself.
