### ISSUE TITLE
[BUG]New-PnPSite: The value cannot be an empty string. (Parameter 'oldValue') 

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/powershell#4491]
### Expected behavior 
The following should create a site 
`$newSite = New-PnPSite -Type TeamSiteWithoutMicrosoft365Group -Owner $user.Id  -Url "https://myTenant.sharepoint.com/sites/Archive27/" -Title "PDF Archive 27" -SiteDesignId $addSiteDesign.Id  -Description "PDF Archive for clients starting with 27" -Connection $connection`

### Actual behavior 
 I get error `New-PnPSite: The value cannot be an empty string. (Parameter 'oldValue') `

### Steps to reproduce behavior
The same happens without -SiteDesignId $addSiteDesign.Id  so it is not the problem

### What is the version of the Cmdlet module you are running?
2.12.3     pnp.powershell tried 2.11.0 and got same results.

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows
Powershell 7.4.6

Please help

**Comment by jackpoz** [comment]
Could you please append `-ErrorAction:Stop` as additional parameter to `New-PnPSite` and then run `Get-PnPException | select *` after the error occurs ? It will show a lot more details useful to troubleshoot the issue.

What connection method did you use ?

**Comment by jackpoz** [comment]
I was able to reproduce the issue:
>Message          : The value cannot be an empty string. (Parameter 'oldValue')
Stacktrace       :    at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
                      at System.String.Replace(String oldValue, String newValue)
                      at PnP.Framework.Sites.SiteCollection.GetRequestPayload(SiteCreationInformation
                   siteCollectionCreationInformation)
                      at PnP.Framework.Sites.SiteCollection.CreateAsync(ClientContext clientContext,
                   TeamNoGroupSiteCollectionCreationInformation siteCollectionCreationInformation, Int32
                   delayAfterCreation, Boolean noWait)
                      at PnP.Framework.Sites.SiteCollection.Create(ClientContext clientContext,
                   TeamNoGroupSiteCollectionCreationInformation siteCollectionCreationInformation, Int32
                   delayAfterCreation, Boolean noWait)
                      at PnP.PowerShell.Commands.NewSite.ExecuteCmdlet() in
                   C:\personal\PnP\powershell\src\Commands\Admin\NewSite.cs:line 225
                      at PnP.PowerShell.Commands.Base.PnPConnectedCmdlet.ProcessRecord() in
                   C:\personal\PnP\powershell\src\Commands\Base\PnPConnectedCmdlet.cs:line 53

**Comment by jackpoz** [comment]
@Ofer-Gal this happens because the url has "/" at the end. Use "https://myTenant.sharepoint.com/sites/Archive27" instead without the / and it will work.

I will open a PR to fix this, but at least you have a work around for the time being.

**Comment by Ofer-Gal** [comment]
Now the error is:"{"SiteId":"","SiteStatus":3,"SiteUrl":""}"
`PS D:\DATA\Sources\Repos\Powershell\PDF-Archive> Get-PnPException | select *                                                

Message          : {"SiteId":"","SiteStatus":3,"SiteUrl":""}
Stacktrace       :    at PnP.Framework.Sites.SiteCollection.CreateAsync(ClientContext clientContext, String owner, Dictiona
                   ry`2 payload, Int32 delayAfterCreation, Int32 maxRetryCount, Int32 retryDelay, Boolean noWait)
                      at PnP.Framework.Sites.SiteCollection.CreateAsync(ClientContext clientContext, TeamNoGroupSiteCollect
                   ionCreationInformation siteCollectionCreationInformation, Int32 delayAfterCreation, Boolean noWait)
                      at PnP.Framework.Sites.SiteCollection.Create(ClientContext clientContext, TeamNoGroupSiteCollectionCr
                   eationInformation siteCollectionCreationInformation, Int32 delayAfterCreation, Boolean noWait)
                      at PnP.PowerShell.Commands.NewSite.ExecuteCmdlet() in c:\build\src\Commands\Admin\NewSite.cs:line 177
                      at PnP.PowerShell.Commands.Base.PnPConnectedCmdlet.ProcessRecord() in c:\build\src\Commands\Base\PnPC 
                   onnectedCmdlet.cs:line 53
ScriptLineNumber : 38
InvocationInfo   : System.Management.Automation.InvocationInfo
Exception        : System.Exception: {"SiteId":"","SiteStatus":3,"SiteUrl":""}
                      at PnP.Framework.Sites.SiteCollection.CreateAsync(ClientContext clientContext, String owner, Dictiona 
                   ry`2 payload, Int32 delayAfterCreation, Int32 maxRetryCount, Int32 retryDelay, Boolean noWait)
                      at PnP.Framework.Sites.SiteCollection.CreateAsync(ClientContext clientContext, TeamNoGroupSiteCollect 
                   ionCreationInformation siteCollectionCreationInformation, Int32 delayAfterCreation, Boolean noWait)      
                      at PnP.Framework.Sites.SiteCollection.Create(ClientContext clientContext, TeamNoGroupSiteCollectionCr 
                   eationInformation siteCollectionCreationInformation, Int32 delayAfterCreation, Boolean noWait)
                      at PnP.PowerShell.Commands.NewSite.ExecuteCmdlet() in c:\build\src\Commands\Admin\NewSite.cs:line 177 
                      at PnP.PowerShell.Commands.Base.PnPConnectedCmdlet.ProcessRecord() in c:\build\src\Commands\Base\PnPC 
                   onnectedCmdlet.cs:line 53
CorrelationId    : b13c5fa1-900a-6000-d037-f0cc311f66cf
TimeStampUtc     : 31/10/2024 08:08:17 AM`

I checked the url has no existing site.
Thank you

**Comment by Ofer-Gal** [comment]
After removing the last / from the url the error is "Now the error is:"{"SiteId":"","SiteStatus":3,"SiteUrl":""}"" when using  -Type CommunicationSite or -Type TeamSiteWithoutMicrosoft365Group 
and I checked the recycle bin. No trace.

**Comment by Ofer-Gal** [comment]
It was  Entra ID object id because in one of the earlier tests it did not like the someone@somewhere and gave an error.
This time I tried it and all was working as expected.😂
Thank you.
