### ISSUE TITLE
[BUG] Get-PnPSiteTemplate Error While Generating Template

### ISSUE THREAD

**Issue by teofilosalgado** [pnp/powershell#540]
### Reporting an Issue or Missing Feature
The `Get-PnPSiteTemplate` is failing to create a template for a given site. I've tested the site beforehand with `Test-PnPSite` and no errors were found.

### Expected behavior 
The `Get-PnPSiteTemplate` command should create an XML template representing the given site.

### Actual behavior 
The command is returning the following error:
```
Get-PnPSiteTemplate : Oops...seems we end up here anyway...check PnP.Framework code to understand what was here
At C:\Users\joaosalgado\workspace\SharePointBackupTools\src\Export-SharePointSiteTemplate.ps1:45 char:9
+         Get-PnPSiteTemplate `
+         ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPSiteTemplate], Exception
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Provisioning.Site.GetSiteTemplate
```
After running `Get-PnPException` I got the following stack:
```
Message          : Oops...seems we end up here anyway...check PnP.Framework code to understand what was here
Stacktrace       :    at PnP.Core.Model.SharePoint.PageWebPart.FromHtml(IElement element)
                      at PnP.Core.Model.SharePoint.Page.LoadFromHtml(String html, String pageHeaderHtml)
                      at PnP.Core.Model.SharePoint.Page.<LoadPageAsync>d__121.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at PnP.Core.Model.SharePoint.Page.<LoadPagesAsync>d__93.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at PnP.Core.Model.SharePoint.Web.<GetPagesAsync>d__282.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at PnP.Core.Model.SharePoint.Web.GetPages(String pageName)
                      at Microsoft.SharePoint.Client.PageExtensions.LoadClientSidePage(Web web, String pageName)
                      at PnP.Framework.Provisioning.ObjectHandlers.Utilities.ClientSidePageContentsHelper.ExtractClientSidePage(Web 
                   web, ProvisioningTemplate template, ProvisioningTemplateCreationInformation creationInfo, PnPMonitoredScope 
                   scope, PageToExport page)
                      at PnP.Framework.Provisioning.ObjectHandlers.ObjectClientSidePageContents.ExtractObjects(Web web, 
                   ProvisioningTemplate template, ProvisioningTemplateCreationInformation creationInfo)
                      at PnP.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.GetRemoteTemplate(Web web, 
                   ProvisioningTemplateCreationInformation creationInfo)
                      at PnP.PowerShell.Commands.Provisioning.Site.GetSiteTemplate.ExtractTemplate(XMLPnPSchemaVersion schema, 
                   String path, String packageName, ExtractConfiguration configuration)
                      at PnP.PowerShell.Commands.Provisioning.Site.GetSiteTemplate.ExecuteCmdlet()
                      at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord()
```
### Steps to reproduce behavior
Just run the following command in a Powershell session.
```
        Get-PnPSiteTemplate `
            -Out $TemplatePath `
            -IncludeAllTermGroups `
            -IncludeSiteCollectionTermGroup `
            -IncludeSiteGroups `
            -PersistBrandingFiles `
            -PersistPublishingFiles `
            -IncludeNativePublishingFiles `
            -IncludeAllPages `
            -Handlers All `
            -Schema LATEST `
            -Force;
```
### What is the version of the Cmdlet module you are running?
1.5.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@teofilosalgado - I have no issue on my side - And I tried on v.1.5.0 - Windows/MacOS
Can you try on a different site, or newly created site? How do you connect to your site?

![image](https://user-images.githubusercontent.com/25181757/113354643-601e1280-9337-11eb-9182-5ef4dedebe35.png)

![image](https://user-images.githubusercontent.com/25181757/113354316-ea19ab80-9336-11eb-9bb3-ad245d6590fd.png)

**Comment by teofilosalgado** [comment]
Oh sorry, I forgot to add more information about the site I'm working on in the issue. So, basically, the issue is happening only on one of my sites. I am not sure if it's related to the site size or something because all of my other sites have like 4 or 5 pages and this one, in particular, is over 700. Also, I'm don't know if it's a known issue with a specific WebPart, this site uses basically everything SharePoint Online has to offer so it would probably suffer.

**Comment by veronicageek** [comment]
I still have no issue using `-Interactive` with 700+ pages, so it might be coming from somewhere else. 
Will wait for inputs from @gautamdsheth and/or @erwinvanhunen if there's anything in the background that might explain this error message (which I've never seen before).

**Comment by teofilosalgado** [comment]
Okay, thanks 😊.
