### ISSUE TITLE
Get-PnPGroupPermissions In Spanish Sub Site Return Error Message: Solicitud no válida.

### ISSUE THREAD

**Issue by Adhanj** [pnp/powershell#574]
### Reporting an Issue or Missing Feature
Issue

### Expected behavior 
Get Permissions of groups

### Actual behavior 
Error message : Solicitud no válida.
Message          : Solicitud no válida.
Stacktrace       :    at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord() in c:\PnPPowerShell\src\Commands\Base\PnPSharePointCmdlet.cs:line 91
                      at System.Management.Automation.CommandProcessor.ProcessRecord()
ScriptLineNumber : 1

### Steps to reproduce behavior
Connect-PnpOnline to a site with special character in Url i.e. https://mytenant.sharepoint.com/sites/SiteCollection/Subsite1/Subsite3/Reunión Mensual Comité Operaciones
Get-pnpgroup |%{Get-PnPGroupPermissions -Identity $_.ID}

### What is the version of the Cmdlet module you are running?
1.5.0

### Which operating system/environment are you running PnP PowerShell on?
[x] Windows

**Comment by veronicageek** [comment]
@Adhanj - Can you post a screenshot of the URL, and that you can connect to it?

**Comment by Adhanj** [comment]
Yes I am able to connect to it and Get-Pnpgroup works. The error occurs when I try to get group permission as shown below.

Get-PnPGroup -Includes ID,Title,LoginName,PrincipalType -ErrorAction SilentlyContinue | 
        Where-Object { $_.Title -notlike "SharingLinks.*" -and $_.Title -notlike "Limited Access*" } |
        ForEach-Object {
            $GroupPermission = Get-PnPGroupPermissions -Identity $_.ID -ErrorAction SilentlyContinue | Where-Object { $_.Hidden -like "False" } 
            If ($GroupPermission.RoleTypeKind -eq "Administrator") {
                $Users += [pscustomobject]@{
                    Title = $_.Title
                    LoginName = $_.LoginName
                    PrincipalType = $_.PrincipalType
                }
            }
        }

**Comment by veronicageek** [comment]
I'd be curious to see the URL with special characters if you can. On the other hand, if the `Get-PnPGroup` works, could there be that your groups have special characters? Something similar to issue #389 ?

If I run your script above on a "normal" site, I have no issue (although probably a copy/paste thing, but make sure your objects have the underscores. For example `$.Title` should be `$_.Title`)

Can you also run `Get-PnPException` right after you get the error and post the results here? Thanks

**Comment by Adhanj** [comment]
![image](https://user-images.githubusercontent.com/82011215/114774413-05b48700-9d25-11eb-9325-5f00694d7ebd.png)
See attached.
I tried another subsite that has same parent subsite but without special character and it worked without any error message.

**Comment by Adhanj** [comment]
Get-PnPException


Message          : Solicitud no válida.
Stacktrace       :    at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord() in c:\PnPPowerShell\src\Commands\Base\PnPSharePointCmdlet.cs:line 91
                      at System.Management.Automation.CommandProcessor.ProcessRecord()
ScriptLineNumber : 5

**Comment by veronicageek** [comment]
What is that `Get-SiteConnection` ?

**Comment by Adhanj** [comment]
That just function that runs Connect-pnponline and pass client id/secret

**Comment by rom-1** [comment]
> I'd be curious to see the URL with special characters if you can. On the other hand, if the `Get-PnPGroup` works, could there be that your groups have special characters? Something similar to issue #389 ?

This is definitely the same issue as #389 ! _Set-PnPGrouppermissions_ and _Get-PnPGrouppermissions_ both have problems with special characters like german umlauts, and this is an issue since a few versions. Unfortunately #389 ist going to be closed in 14 days due to no activity 😢

![111635464-c95e3b80-87f7-11eb-91a4-2bc880084cda 1](https://user-images.githubusercontent.com/37835829/115713498-5b68df00-a376-11eb-9b47-741e71bd94fd.png)

**Comment by veronicageek** [comment]
@rom-1 - Thanks, I've also removed the `no-activity` label on issue #389

**Comment by Adhanj** [comment]
This one may not entirely similar issue as the group title don't have special character and when passing group id, Get-PnPGroupPermissions still generates error message. I don't know the underlying mechanism but only thing I found is the site has special characters in it. @veronicageek , I can show you this behavior via remote session if needed.

**Comment by erwinvanhunen** [comment]
After some more debugging we think we found the reason (haven't tested a solution yet). We're taking this up with the Core SDK team as the issue occurs on Core SDK level.
