### ISSUE TITLE
Exception of type 'PnP.PowerShell.Commands.Model.Teams.GraphException' was thrown

### ISSUE THREAD

**Issue by JulienValentin78** [pnp/powershell#752]
Hi Team,

Having an issue with my Cx on step 2 when trying to create Azure AD Apps with provided cmdlet from documentation :

_Initialize-PnPPowerShellAuthentication -ApplicationName ModernizationScannerApp -Tenant mycustomer.onmicrosoft.com -Scopes "SPO.Sites.FullControl.All","MSGraph.Group.Read.All"  -OutPath c:\temp -CertificatePassword (ConvertTo-SecureString -String "password" -AsPlainText -Force)_

_Result :_

Initialize-PnPPowerShellAuthentication : Exception of type 'PnP.PowerShell.Commands.Model.Teams.GraphException' was thrown.
At line:1 char:1
+ Initialize-PnPPowerShellAuthentication -ApplicationName Modernization ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : NotSpecified: (:) [Initialize-PnPPowerShellAuthentication], GraphException
+ FullyQualifiedErrorId : PnP.PowerShell.Commands.Model.Teams.GraphException,PnP.PowerShell.Commands.Base.InitializePowerShellAut
hentication

Could you help me ?

Many thanks

**Comment by gautamdsheth** [comment]
Hello, can you do a `Get-PnPException` after the error is thrown and paste the stack trace here ?

**Comment by JulienValentin78** [comment]
For sure !

PS C:\Users\XXXXX> Get-PnPException

CorrelationId :
TimeStampUtc : 1/1/0001 12:00:00 AM
Message : Exception of type 'PnP.PowerShell.Commands.Model.Teams.GraphException' was thrown.
Stacktrace : at PnP.PowerShell.Commands.Utilities.REST.GraphHelper.<SendMessageAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at PnP.PowerShell.Commands.Utilities.REST.GraphHelper.<PostInternalAsync>d__11`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at PnP.PowerShell.Commands.Utilities.REST.GraphHelper.<PostAsync>d__7`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at PnP.PowerShell.Commands.Base.InitializePowerShellAuthentication.ProcessRecord()
at System.Management.Automation.CommandProcessor.ProcessRecord()
ScriptLineNumber : 1

**Comment by JulienValentin78** [comment]
Hi Team ! Any update on this issue ?

**Comment by gautamdsheth** [comment]
Hey @JulienValentin78, have fixed it. Please give it a try tomorrow and let us know how it goes !
Thanks for reporting !
