### ISSUE TITLE
[BUG] When use Set-PnPPageWebPart cmdlet to try update a Page in Draft state

### ISSUE THREAD

**Issue by jmunozcastro** [pnp/powershell#783]
### Reporting an Issue or Missing Feature
When a PowerShell script is run to update a property of any web part using Set-PnPPageWebPart Cmdlet if the page is in Draft state, a throw error is displayed like following:

At line:1 char:1
+ Set-PnPPageWebPart -Page $clientPage -Identity $webpart.InstanceId -P ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Set-PnPPageWebPart], CsomServiceException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Pages.SetClientSideWebPart

When the Get-PnPException Cmdlet run, give us the next error
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Message          : CSOM service exception
    Stacktrace       :    at PnP.Core.Services.BatchClient.ProcessCsomBatchResponse(CsomBatch csomBatch, String batchResponse, HttpStatusCode statusCode)
                      at PnP.Core.Services.BatchClient.<ExecuteCsomBatchAsync>d__53.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at PnP.Core.Services.BatchClient.<ExecuteBatch>d__36.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at PnP.Core.Model.BaseDataModel`1.<RequestAsync>d__99.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at PnP.Core.Model.BaseDataModel`1.<RawRequestAsync>d__102.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at PnP.Core.Model.SharePoint.ListItem.<SystemUpdateAsync>d__75.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at PnP.Core.Model.SharePoint.Page.<SaveAsync>d__129.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at PnP.Core.Model.SharePoint.Page.Save(String pageName)
                      at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord()

*** That issue is not exists in the 1.5 previous version

### Expected behavior 
Update the web part although it is located in a draft page

### Actual behavior 
An error is displayed indicating that occurred a CsomServiceException when the Set-PnPPageWebPart Cmdlet was executed like:
+ Set-PnPPageWebPart -Page $clientPage -Identity $webpart.InstanceId -P ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Set-PnPPageWebPart], CsomServiceException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Pages.SetClientSideWebPart
 
And the web part was not updated
### Steps to reproduce behavior
1) Use a page into a folder in draft state like: /SitePages/Templates/index.aspx
2) Execute the next commands
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    $pageTitle = "/Templates/index.aspx"
    $clientPage = Get-PnPClientSidePage -Identity $pageTitle
    $webpart = $clientPage.Controls[0]
    $webpartJson = $webpart.PropertiesJson
    
    /*** Make the following change or any other change to the web part ***/
    $webpartobj = ConvertFrom-Json -InputObject $webpartJson
    $oldIconName = "oldIconName"
    $newIconName = "newOne"
    $webpartobj.content = $webpartobj.content.Replace($oldIconName, $newIconName)
    $webpartJson = ConvertTo-Json $webpartobj
    /*** end change ***/
    
   /*** This cmdlet throw the error ***/
    Set-PnPPageWebPart -Page $clientPage -Identity $webpart.InstanceId -PropertiesJson $webpartJson 

### What is the version of the Cmdlet module you are running?
Manifest   1.6.0      PnP.PowerShell
NOTE in 1.5.0  not existed the issue  

### Which operating system/environment are you running PnP PowerShell on?
- [ x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by jmunozcastro** [comment]
I appreciate so much the feedback or if Are there any thing that is not clear let me know to complete the issue with the needed stuff, thank you in advance! ;)

**Comment by jmunozcastro** [comment]
Someone there? Please let me know if the issue reported was fixed in your last version, or if I forgot to indicate something in the error report please, let me know to give you the needed information
