### ISSUE TITLE
[BUG] - Error with Add-PnPHubSiteAssociation

### ISSUE THREAD

**Issue by jcizek84** [pnp/powershell#805]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

No cmdlet related to HubSite actually works as described. Any cmdlet that I try to run returns "file not found" - with no further description. I searched for the error, reinstalled all required PowerShell modules etc.  Register-PnPManagementShellAccess has been ran on tenant and succesfully registered etc. 

### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting

### Expected behavior 
Running cmdlet: Add-PnPHubSiteAssociation -Site "https://demokpcs.sharepoint.com/sites/test_site_1/" -HubSite "https://demokpcs.sharepoint.com/sites/demoportal" 
should update the settings of PnPTenantSite, precisely the HubSiteID attribute. 

### Actual behavior 
Running the cmdlet (Add-PnPHubSiteAssociation -Site "https://demokpcs.sharepoint.com/sites/test_site_1/" -HubSite "https://demokpcs.sharepoint.com/sites/demoportal" ) actually returns: 

PS C:\Users\username\test> Add-PnPHubSiteAssociation -Site "https://demokpcs.sharepoint.com/sites/test_site_1" -HubSite "https://demokpcs.sharepoint.com/sites/demoportal"
Add-PnPHubSiteAssociation: File not found.

Detail of error: 
ErrorRecord                 : Soubor nebyl nalezen. (file not found)
WasThrownFromThrowStatement : False
TargetSite                  : System.Collections.ObjectModel.Collection`1[System.Management.Automation.PSObject] Invoke(System.Collections.IEnumerable)        
StackTrace                  :    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
                                 at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
                                 at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
                                 at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 outpu
                              t, PSInvocationSettings settings)
                                 at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSI
                              nvocationSettings settings)
                                 at System.Management.Automation.PowerShell.Invoke[T](IEnumerable input, PSInvocationSettings settings)
                                 at Microsoft.PowerShell.EditorServices.Services.PowerShellContextService.<>c__DisplayClass89_0`1.<ExecuteCommandAsync>b__0() i
                              n D:\a\1\s\src\PowerShellEditorServices\Services\PowerShellContext\PowerShellContextService.cs:line 775
                                 at System.Threading.Tasks.Task`1.InnerInvoke()
                                 at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext,
                               ContextCallback callback, Object state)
                              --- End of stack trace from previous location ---
                                 at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
                              --- End of stack trace from previous location ---
                                 at Microsoft.PowerShell.EditorServices.Services.PowerShellContextService.ExecuteCommandAsync[TResult](PSCommand psCommand, Str
                              ingBuilder errorMessages, ExecutionOptions executionOptions) in D:\a\1\s\src\PowerShellEditorServices\Services\PowerShellContext\
                              PowerShellContextService.cs:line 775
                                 at Microsoft.PowerShell.EditorServices.Services.PowerShellContextService.ExecuteCommandAsync[TResult](PSCommand psCommand, Str
                              ingBuilder errorMessages, ExecutionOptions executionOptions) in D:\a\1\s\src\PowerShellEditorServices\Services\PowerShellContext\
                              PowerShellContextService.cs:line 820
Message                     : The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Soubor ne
                              byl nalezen.
Data                        : {System.Management.Automation.Interpreter.InterpretedFrameInfo}
InnerException              :
HelpLink                    :
Source                      : System.Management.Automation
HResult                     : -2146233087

### Steps to reproduce behavior
run:  Add-PnPHubSiteAssociation -Site "https://demokpcs.sharepoint.com/sites/test_site_1" -HubSite "https://demokpcs.sharepoint.com/sites/demoportal"

or

Grant-PnPHubSiteRights -Identity "https://demokpcs.sharepoint.com/sites/demoportal" -Principals "user@demokpcs.onmicrosoft.com" 

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

1.6.8-nightly

### Which operating system/environment are you running PnP PowerShell on?
- [ X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@jcizek84 - I have tried with the nightly releases `1.6.10` and `1.6.33` and no issue on my side. Can you please update and try again? Thanks

![image](https://user-images.githubusercontent.com/25181757/125164186-dfb64b80-e188-11eb-8b15-299bc1e358e8.png)
