### ISSUE TITLE
[BUG] Export-PnPFlow - Method not found

### ISSUE THREAD

**Issue by robertcaretta** [pnp/powershell#831]
### Reporting an Issue or Missing Feature
Export-PnPFlow is not exporting the zip file as expected. As a test I am attempting to export a single flow that I am the creator/owner. I am also a Office 365 tenant administrator with the proper rights to run powershell. We do have the PnP Management Shell application installed in Azure AD, and my user account has access to it.

I am able to run Import-Module -Name PnP.PowerShell just fine. The module is installed under the scope of the current user.

### Expected behavior 
Should export zip file.

### Actual behavior 
ERROR: _Export-PnPFlow : Method not found: 'Int32 System.Text.Encodings.Web.TextEncoder.FindFirstCharacterToEncodeUtf8(System.ReadOnlySpan`1<Byte>)'._

When I run Get-PnPException I see this:
_Message          : Method not found: 'Int32 System.Text.Encodings.Web.TextEncoder.FindFirstCharacterToEncodeUtf8(System.ReadOnlySpan`1<Byte>)'.
Stacktrace       :    at System.Text.Json.JsonWriterHelper.NeedsEscaping(ReadOnlySpan`1 value, JavaScriptEncoder encoder)
                      at System.Text.Json.JsonEncodedText.EncodeHelper(ReadOnlySpan`1 utf8Value, JavaScriptEncoder encoder)
                      at System.Text.Json.JsonPropertyInfo.DeterminePropertyName()
                      at System.Text.Json.JsonPropertyInfo.GetPolicies()
                      at System.Text.Json.JsonClassInfo.CreateProperty(Type declaredPropertyType, Type runtimePropertyType, Type implementedPropertyType,
                   PropertyInfo propertyInfo, Type parentClassType, JsonConverter converter, JsonSerializerOptions options)
                      at System.Text.Json.JsonClassInfo.AddProperty(Type propertyType, PropertyInfo propertyInfo, Type classType, JsonSerializerOptions options)    
                      at System.Text.Json.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)
                      at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type classType)
                      at System.Text.Json.WriteStackFrame.Initialize(Type type, JsonSerializerOptions options)
                      at System.Text.Json.JsonSerializer.WriteCore(Utf8JsonWriter writer, Object value, Type type, JsonSerializerOptions options)
                      at System.Text.Json.JsonSerializer.WriteCore(PooledByteBufferWriter output, Object value, Type type, JsonSerializerOptions options)
                      at System.Text.Json.JsonSerializer.WriteCoreString(Object value, Type type, JsonSerializerOptions options)
                      at PnP.PowerShell.Commands.Utilities.REST.RestHelper.<PostAsync>d__11.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at PnP.PowerShell.Commands.Utilities.REST.RestHelper.<PostAsync>d__13`1.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at PnP.PowerShell.Commands.Graph.ExportFlow.ExecuteCmdlet()
                      at PnP.PowerShell.Commands.Base.BasePSCmdlet.ProcessRecord()
                      at System.Management.Automation.CommandProcessor.ProcessRecord()
ScriptLineNumber : 1_

### Steps to reproduce behavior
`Export-PnPFlow -Environment $defaultEnvGUID -Identity '0b32625d-e991-422a-97bb-69c57ff326b6' -PackageDisplayName "ExportedFlow" -AsZipPackage -OutPath "ExportedFlow.zip" -Force`

### What is the version of the Cmdlet module you are running?
1.6.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by robertcaretta** [comment]
This works fine. 
`Export-PnPFlow -Environment $defaultEnvGUID -Identity '0b32625d-e991-422a-97bb-69c57ff326b6'`

However, as soon as I try the switch -AsZipPackage I get errors. I also tried on a second machine and was able to reproduce the results on that machine as well.

**Comment by veronicageek** [comment]
@robertcaretta - I have tried with `1.6.0` on MacOS and Windows, and no issue on my side. Can you please try again?

![image](https://user-images.githubusercontent.com/25181757/122810987-e22f2f00-d2c7-11eb-9b85-9db7d973d2c7.png)

![image](https://user-images.githubusercontent.com/25181757/122811032-ed825a80-d2c7-11eb-84dd-d067a4836e90.png)

**Comment by robertcaretta** [comment]
@veronicageek - Unfortunately, it doesn't work for me. I can connect to the tenant, check my context, etc. just fine.   Does the module need to be installed at the machine level perhaps? I have it installed only at the scope of my user account.

![20210621_Pic1](https://user-images.githubusercontent.com/1613085/122818365-b3509300-d29e-11eb-8d57-54bd5530a8b4.png)

![20210621_Pic2](https://user-images.githubusercontent.com/1613085/122818374-b64b8380-d29e-11eb-88d5-45d8c904973e.png)

**Comment by robertcaretta** [comment]
Is there a dependency on Powershell 7.1?  We are still using 5.1 in our environment.
![20210621_Pic3](https://user-images.githubusercontent.com/1613085/122819317-e8a9b080-d29f-11eb-965c-2d8b1596ff75.png)

**Comment by robertcaretta** [comment]
$gm = Get-Module -Name PnP.PowerShell
$gm.ExportedCmdlets

I can see the cmdlet is available.
![20210621_Pic4](https://user-images.githubusercontent.com/1613085/122819639-5655dc80-d2a0-11eb-9a2b-9240fead0aa2.png)

**Comment by veronicageek** [comment]
@robertcaretta -  Thinking that might also be a VSCode problem here following on your issue #860 
Can you please try in the console or ISE to confirm you have the same problem?

**Comment by robertcaretta** [comment]
That is indeed the issue. I have requested that my company push out the latest VS Code to me.   Would you mind asking your colleagues if they have run into this?  I'd really like to know why the ISE works and not VS Code.   We are supposed to be moving away from ISE. :) 

![image](https://user-images.githubusercontent.com/1613085/123474336-6e3ea080-d5bf-11eb-8726-aa421f31e987.png)

**Comment by veronicageek** [comment]
@robertcaretta - Thank you for checking. I'm going to also close this issue also as not PnP PowerShell related. 

But I want to mention that because this repo is community maintained (on our own personal time and not by Microsoft), unfortunately we do not have the time nor the resources/capacity to be troubleshooting other platforms.

Still tagging @gautamdsheth / @erwinvanhunen / @KoenZomers in case they have some insights or they have seen this before.

**Comment by robertcaretta** [comment]
Can we re-open this ticket please? There is definitely something not quite right with the Export-PnPFlow cmdlet.  In ISE I am seeing partial success.  There are a total of 42 flows in the Default environment, and only 13 export. No errors are thrown. 

![image](https://user-images.githubusercontent.com/1613085/123667220-90266600-d7ff-11eb-99c4-e8dc365524b8.png)

**Comment by veronicageek** [comment]
@robertcaretta - Please open a new issue because this is different. Also feel free to mention issue #617 which might be similar. Thanks
