### ISSUE TITLE
[BUG] PNP Powershell module stop functioning after a TCP Port test

### ISSUE THREAD

**Issue by olivier4470** [pnp/powershell#929]
I have a script that check my SCCM infra health and write results to a sharepoint.
**Environment of my script : W2K12 , Powershell V5.1 + PNP.Powershell V1.6.0**

Strangely PNP.Powershell stop functioning if you do a test on Y/N a TCP port is opened

Basically i do this : 	
**$Result = Invoke-Command -ComputerName $s -ScriptBlock { try{New-Object System.Net.Sockets.TcpClient($Using:t, $Using:tcpport)} catch{}}**
						
so in clear i remotely test from a server if a port is open Y or N to know if my infrastructure is working 

If one port is closed or filtered , then all futur call to cmdlet of PNP.Powershell failed like : 
**Set-PnpListItem : Exception has been thrown by the target of an invocation.**

if in the same test everything is ok (so open meaning the cmdlet upper worked nicely) then all the PNP call succeed.

I tried other method like using an exe PORTQRY or opening a PSSESSION ==> Same result
i can't use TEST-NETCONNECTION because on some remote server i'm still in W2K12 with an old powershell v3

i believe something with io stack but no clue on how to solve this

other precision : for each PNP call i open connection , do the call and close connection (so no timeout possible), i tried also leaving the connection open an do all my call ==> The same

I have this issue ONLY with a TCP PORT TEST 

![pnpissue](https://user-images.githubusercontent.com/87722599/126383770-410e8813-db91-406c-a4f1-6a16e98c1adc.JPG)

**Comment by olivier4470** [comment]
May be it can help here is the stacktrace when error occurs : 

PS CNG:\> $x.Exception.StackTrace
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters
, CultureInfo culture)
   at Microsoft.SharePoint.Client.ClientContextExtensions.<>c__DisplayClass10_0.<Clone>b__0(Object oSender, WebRequestEv
entArgs webRequestEventArgs)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Microsoft.SharePoint.Client.ClientRuntimeContext.OnExecutingWebRequest(WebRequestEventArgs args)
   at Microsoft.SharePoint.Client.ClientContext.GetWebRequestExecutor()
   at Microsoft.SharePoint.Client.ClientContext.<GetFormDigestInfoPrivateAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<EnsureFormDigestAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 re
tryCount, String userAgent)
   at PnP.PowerShell.Commands.PnPWebCmdlet.GetWeb()
   at PnP.PowerShell.Commands.Lists.SetListItem.ExecuteCmdlet()
   at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord()

**Comment by olivier4470** [comment]
and the whole Exception object : 
Message        : Exception has been thrown by the target of an invocation.
Data           : {CorrelationId, TimeStampUtc}
InnerException : System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a
                 receive. ---> System.Management.Automation.PSInvalidOperationException: There is no Runspace
                 available to run scripts in this thread. You can provide one in the DefaultRunspace property of the
                 System.Management.Automation.Runspaces.Runspace type. The script block you attempted to invoke was:
                 $true
                    at System.Management.Automation.ScriptBlock.GetContextFromTLS()
                    at System.Management.Automation.ScriptBlock.InvokeAsDelegateHelper(Object dollarUnder, Object
                 dollarThis, Object[] args)
                    at lambda_method(Closure , Object , X509Certificate , X509Chain , SslPolicyErrors )
                    at System.Net.ServerCertValidationCallback.Callback(Object state)
                    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext,
                 ContextCallback callback, Object state, Boolean preserveSyncCtx)
                    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback
                 callback, Object state, Boolean preserveSyncCtx)
                    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback
                 callback, Object state)
                    at System.Net.ServerCertValidationCallback.Invoke(Object request, X509Certificate certificate,
                 X509Chain chain, SslPolicyErrors sslPolicyErrors)
                    at System.Net.Security.SecureChannel.VerifyRemoteCertificate(RemoteCertValidationCallback
                 remoteCertValidationCallback, ProtocolToken& alertToken)
                    at System.Net.Security.SslState.CompleteHandshake(ProtocolToken& alertToken)
                    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message,
                 AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count,
                 AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message,
                 AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count,
                 AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message,
                 AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count,
                 AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message,
                 AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer,
                 AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
                    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext,
                 ContextCallback callback, Object state, Boolean preserveSyncCtx)
                    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback
                 callback, Object state, Boolean preserveSyncCtx)
                    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback
                 callback, Object state)
                    at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
                    at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
                    at System.Net.PooledStream.Write(Byte[] buffer, Int32 offset, Int32 size)
                    at System.Net.ConnectStream.WriteHeaders(Boolean async)
                    --- End of inner exception stack trace ---
                    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
                    at System.Net.WebClient.DownloadData(Uri address)
                    at PnP.Framework.Utilities.TokenHelper.GetMetadataDocument(String realm)
                    at PnP.Framework.Utilities.TokenHelper.GetStsUrl(String realm)
                    at PnP.Framework.Utilities.TokenHelper.GetAppOnlyAccessToken(String targetPrincipalName, String
                 targetHost, String targetRealm)
                    at PnP.Framework.Utilities.ACSTokenGenerator.GetToken(Uri siteUrl)
                    at PnP.Framework.AuthenticationManager.<>c__DisplayClass68_0.<GetAccessTokenContext>b__0(Object
                 sender, WebRequestEventArgs args)
                    at Microsoft.SharePoint.Client.ClientRuntimeContext.OnExecutingWebRequest(WebRequestEventArgs args)
TargetSite     : System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
StackTrace     :    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig,
                 Boolean constructor)
                    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters,
                 Object[] arguments)
                    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder,
                 Object[] parameters, CultureInfo culture)
                    at Microsoft.SharePoint.Client.ClientContextExtensions.<>c__DisplayClass10_0.<Clone>b__0(Object
                 oSender, WebRequestEventArgs webRequestEventArgs)
                    at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
                    at Microsoft.SharePoint.Client.ClientRuntimeContext.OnExecutingWebRequest(WebRequestEventArgs args)
                    at Microsoft.SharePoint.Client.ClientContext.GetWebRequestExecutor()
                    at Microsoft.SharePoint.Client.ClientContext.<GetFormDigestInfoPrivateAsync>d__37.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.SharePoint.Client.ClientContext.<EnsureFormDigestAsync>d__36.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__28.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__6.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext
                 clientContext, Int32 retryCount, String userAgent)
                    at PnP.PowerShell.Commands.PnPWebCmdlet.GetWeb()
                    at PnP.PowerShell.Commands.Lists.SetListItem.ExecuteCmdlet()
                    at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord()
HelpLink       :
Source         : mscorlib
HResult        : -2146232828

**Comment by olivier4470** [comment]
issue was not related to what i describer but an issue in .net call while interrogating an url certificate
