### ISSUE TITLE
ConvertTo-PnPPage - Method not found

### ISSUE THREAD

**Issue by pmisley** [pnp/powershell#941]
I am receiving a Method not found error any time I try to use ConvertTo-PnPPage or the previous ConvertTo-PnPClientSidePage. I have fully removed the module and installed again using v1.6.0.

```
Message          : Method not found: 'System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1<Boolean> Enumerator.MoveNextAsync()'.
Stacktrace       :    at PnP.Core.QueryModel.QueryableExtensions.<ToListAsync>d__15`1.MoveNext()
                      at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
                      at PnP.Core.QueryModel.QueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
                      at PnP.Core.Model.SharePoint.Page.<EnsurePagesLibraryAsync>d__97.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at PnP.Core.Model.SharePoint.Page.<NewPageAsync>d__96.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at PnP.Core.Model.SharePoint.Web.<NewPageAsync>d__284.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at PnP.Core.Model.SharePoint.Web.NewPage(PageLayoutType pageLayoutType)
                      at Microsoft.SharePoint.Client.PageExtensions.AddClientSidePage(Web web, String pageName, Boolean alreadyPersist)
                      at PnP.Framework.Modernization.Transform.PageTransformator.Transform(PageTransformationInformation pageTransformationInformation)
                      at PnP.PowerShell.Commands.Pages.ConvertToClientSidePage.ExecuteCmdlet()
                      at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord()
```

**Comment by veronicageek** [comment]
@pmisley - Please update your module to `1.7.0` released today, and try again. _IF_ it still doesn't work, please fill the below issue template. Thanks.

### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting

### Expected behavior 
Please describe what output you expect to see from the PnP PowerShell Cmdlets

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by pmisley** [comment]
> ### Reporting an Issue or Missing Feature
> Failing to perform a ConvertTo-PnPPage for certain pages
> 
> ### Expected behavior
> Modernizing  Home.aspx ...
> Done
> 
> ### Actual behavior
```
Modernizing  Home.aspx ...
ConvertTo-PnPPage : '0x0A' is invalid within a JSON string. The string should be correctly escaped. LineNumber: 0 | > BytePositionInLine: 84.
At line:10 char:27
+ ... odernPage = ConvertTo-PnPPage -Identity $page.FieldValues["ID"] -Over ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [ConvertTo-PnPPage], JsonReaderException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Pages.ConvertToClientSidePage
Done
```
>
>
> ### Steps to reproduce behavior
```
# Connect to the web holding the pages to modernize
Connect-PnPOnline -Url https://contoso.sharepoint.com/sites/modernizationme -Interactive

# Get all the pages in the site pages library. SitePages is the only supported library for using modern pages
# Use paging (-PageSize parameter) to ensure the query works when there are more than 5000 items in the list
$pages = Get-PnPListItem -List sitepages -PageSize 500

# Iterate over the pages
foreach($page in $pages) 
{ 
    # No need to convert modern pages again
    if ($page.FieldValues["ClientSideApplicationId"] -eq "b6917cb1-93a0-4b97-a84d-7cf49975d4ec" ) 
    { 
        Write-Host "Page " $page.FieldValues["FileLeafRef"] " is modern, no need to modernize it again"
    } 
    else 
    { 
        # Create a modern version of this page
        Write-Host "Modernizing " $page.FieldValues["FileLeafRef"] "..."
        # Use the PageID value instead of the page name in the Identity parameter as that is more performant + it works when there are more than 5000 items in the list
        $modernPage = ConvertTo-PnPPage -Identity $page.FieldValues["ID"] -Overwrite
        Write-Host "Done" -ForegroundColor Green
    }
}

Disconnect-PnPOnline
```
> 
> 
> ### What is the version of the Cmdlet module you are running?
> (you can retrieve this by executing `Get-Module -Name "PnP.PowerShell" -ListAvailable`)
>**1.7.0** 
>
> ### Which operating system/environment are you running PnP PowerShell on?
> * [X]  Windows
> * [ ]  Linux
> * [ ]  MacOS
> * [ ]  Azure Cloud Shell
> * [ ]  Azure Functions
> * [ ]  Other : please specify

**Comment by gautamdsheth** [comment]
@pmisley - is the issue still happening? Can you please try again with the latest nightly build and let us know ?

**Comment by veronicageek** [comment]
Closing as no response.
