### ISSUE TITLE
[BUG] Remove-PnPListItem : Property ServerRelativeUrl was not yet loaded | Batching error

### ISSUE THREAD

**Issue by KoalaScripts** [pnp/powershell#945]
### Reporting an Issue or Missing Feature
When running command `Remove-PnPListItem -List "SitePages" -Identity $File.id -Batch $batch` or any command in the -Batch form i receive following error :  
```
Remove-PnPListItem : Property ServerRelativeUrl was not yet loaded
At line:1 char:1
+ Remove-PnPListItem -List "SitePages" -Identity $File.id -Batch $batch
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Remove-PnPListItem], ClientException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Lists.RemoveListItem
```

### Expected behavior 
Expected behavior would be to add it to the Batch and at the end allow me to invoke the batch

### Actual behavior 
```
Remove-PnPListItem -List "SitePages" -Identity $File.id -Batch $batch
Remove-PnPListItem : Property ServerRelativeUrl was not yet loaded
At line:1 char:1
+ Remove-PnPListItem -List "SitePages" -Identity $File.id -Batch $batch
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Remove-PnPListItem], ClientException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Lists.RemoveListItem
```

```
Set-PnPListItem -list "SitePages" -Identity 1000 -Values $hashTable -Batch $batch
Set-PnPListItem : Property ServerRelativeUrl was not yet loaded
At line:1 char:1
+ Set-PnPListItem -list "SitePages" -Identity 1000 -Values $hashTable - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Set-PnPListItem], ClientException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Lists.SetListItem
```

### Steps to reproduce behavior
Sample code to reproduce the error
```
$Files = Get-pnplistitem -List "SitePages" -PageSize 1
$batch = New-PnPBatch


Foreach($File in $Files){
    
    $File.FieldValues.FileLeafRef
    Remove-PnPListItem -List "SitePages" -Identity $File.id -Batch $batch

}
Invoke-PnPBatch -Batch $batch -Force

```
### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)
1.7.0
### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by KoalaScripts** [comment]
To debug further i ran the Get-PnPExeption command 

Message          : Property ServerRelativeUrl was not yet loaded
Stacktrace       :    at PnP.Core.Model.TransientObject.GetValue[T](String propertyName)
                      at PnP.PowerShell.Commands.Base.PipeBinds.ListPipeBind.GetList(PnPBatch batch, Expression`1[] selectors)
                      at PnP.PowerShell.Commands.Lists.RemoveListItem.ExecuteCmdlet()
                      at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord()
ScriptLineNumber : 1

**Comment by natpdeee** [comment]
Tested this just now and I got the same issue with anything related to Batch. 
Deleting the items manually inside a loop works fine.

`
Message          : Property ServerRelativeUrl was not yet loaded
Stacktrace       :    at PnP.Core.Model.TransientObject.GetValue[T](String propertyName)
                      at PnP.Core.Model.SharePoint.Web.get_ServerRelativeUrl()
                      at PnP.PowerShell.Commands.Base.PipeBinds.ListPipeBind.GetList(PnPBatch batch, Expression[] selectors) in 
                   c:\PnPPowerShell\src\Commands\Base\PipeBinds\ListPipeBind.cs:line 113
                      at PnP.PowerShell.Commands.Lists.RemoveListItem.ExecuteCmdlet() in c:\PnPPowerShell\src\Commands\Lists\RemoveListItem.cs:line 36
                      at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord() in c:\PnPPowerShell\src\Commands\Base\PnPSharePointCmdlet.cs:line 91
`

Any suggestions or further debugging that I can do?

**Comment by sharepointknight** [comment]
I am seeing this same issue with the 1.7.0 version only while trying to use a batch.

**Comment by veronicageek** [comment]
@KoalaScripts @natpdeee @sharepointknight - We're aware that there's a problem with the `-Batch` option and we'll have a look at it when we can.

**Comment by soaway** [comment]
The same issue with "Set-PnPListItem":   "Property ServerRelativeUrl was not yet loaded"
